### ISSUE TITLE
compare functionality dies with special character

### ISSUE THREAD

**Issue by Inf0Junki3** [deadc0de6/dotdrop#1]
Hey there,

  Kudos on the nifty project! Quick one: the compare functionality gave me a UnicodeDecodeError when it hit a special character in my viminfo file. Here's the full exception:

diffing "f_viminfo" VS "~/.viminfo"
Traceback (most recent call last):
  File "/home/inf0junki3/dotfiles/dotdrop/dotdrop/dotdrop.py", line 165, in <module>
    if compare(opts, conf, tmp):
  File "/home/inf0junki3/dotfiles/dotdrop/dotdrop/dotdrop.py", line 86, in compare
    inst.compare(t, tmp, opts['profile'], dotfile.src, dotfile.dst)
  File "/home/inf0junki3/dotfiles/dotdrop/dotdrop/installer.py", line 131, in compare
    templater, profile, src, dst, tmpfolder)
  File "/home/inf0junki3/dotfiles/dotdrop/dotdrop/installer.py", line 118, in _install_to_temp
    return self.install(templater, profile, src, tmpdst), tmpdst
  File "/home/inf0junki3/dotfiles/dotdrop/dotdrop/installer.py", line 31, in install
    return self._handle_file(templater, profile, src, dst)
  File "/home/inf0junki3/dotfiles/dotdrop/dotdrop/installer.py", line 38, in _handle_file
    content = templater.generate(src, profile)
  File "/home/inf0junki3/dotfiles/dotdrop/dotdrop/templategen.py", line 34, in generate
    return self._handle_file(src, profile)
  File "/home/inf0junki3/dotfiles/dotdrop/dotdrop/templategen.py", line 42, in _handle_file
    return self._handle_text_file(src, profile)
  File "/home/inf0junki3/dotfiles/dotdrop/dotdrop/templategen.py", line 46, in _handle_text_file
    template = self.env.get_template(src[l:])
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/usr/local/lib/python3.5/dist-packages/jinja2/loaders.py", line 175, in get_source
    contents = f.read().decode(self.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 1807: invalid start byte

**Comment by deadc0de6** [comment]
Thanks for reporting this !

This is due to bad char in your text files.

There's not much I can do but I implemented a dirty fix in 6ea90ee1d6a7d545bbdba2ededd0e4895b5d8788 that should at least not make dotdrop crash.

What it does is replacing the bad char with a *replacement char* (see [python3 unicode](https://docs.python.org/3/howto/unicode.html) for more info).

This partially solves your issue since the *compare* will now warn you that some part of your text is different (the bad chars have indeed been replaced). 

Let me know if that works for you.

**Comment by Inf0Junki3** [comment]
Cheers mate!
