### ISSUE TITLE
Jinja2 include absolute file path TemplateNotFound

### ISSUE THREAD

**Issue by Eluminae** [deadc0de6/dotdrop#104]
Hello !

I got a problem. I'd like to use jinja2 include in templates, providing an absolute file path, and I got an exception...

my example:
```
{%@@ include base16_root_location + '/qutebrowser/themes/' + color_scheme + '.config.py' @@%}
```

Which give 
```
$ dotdrop install -f
     _       _      _
  __| | ___ | |_ __| |_ __ ___  _ __
 / _` |/ _ \| __/ _` | '__/ _ \| '_ |
 \__,_|\___/ \__\__,_|_|  \___/| .__/  v0.26.1
                               |_|

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/eddie/Dotfiles/programs/dotdrop/dotdrop/dotdrop.py", line 460, in <module>
    if main():
  File "/home/eddie/Dotfiles/programs/dotdrop/dotdrop/dotdrop.py", line 423, in main
    ret = cmd_install(o)
  File "/home/eddie/Dotfiles/programs/dotdrop/dotdrop/dotdrop.py", line 77, in cmd_install
    noempty=dotfile.noempty)
  File "/home/eddie/Dotfiles/programs/dotdrop/dotdrop/installer.py", line 74, in install
    noempty=noempty)
  File "/home/eddie/Dotfiles/programs/dotdrop/dotdrop/installer.py", line 269, in _handle_dir
    actions=actions, noempty=noempty)
  File "/home/eddie/Dotfiles/programs/dotdrop/dotdrop/installer.py", line 231, in _handle_file
    content = templater.generate(src)
  File "/home/eddie/Dotfiles/programs/dotdrop/dotdrop/templategen.py", line 57, in generate
    return self._handle_file(src)
  File "/home/eddie/Dotfiles/programs/dotdrop/dotdrop/templategen.py", line 85, in _handle_file
    return self._handle_text_file(src)
  File "/home/eddie/Dotfiles/programs/dotdrop/dotdrop/templategen.py", line 103, in _handle_text_file
    content = template.render()
  File "/home/eddie/.local/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/eddie/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/eddie/.local/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception                                                                                                        
    reraise(exc_type, exc_value, tb)
  File "/home/eddie/.local/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/eddie/Dotfiles/./config/qutebrowser/config.py", line 38, in top-level template code
    {%@@ include base16_root_location + '/qutebrowser/themes/' + color_scheme + '.config.py' @@%}
  File "/home/eddie/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /home/eddie/Dotfiles/base16/qutebrowser/themes/base16-default-dark.config.py                                                                                                    
```

OFC, by the way, this file is present:
```
$ [ -f '/home/eddie/Dotfiles/base16/qutebrowser/themes/base16-default-dark.config.py' ] && echo "It's here !"
It's here !
```

**Comment by Eluminae** [comment]
In fact, include do not work at all x)) even if I hard code paths, even if the target file is in the same directory.

**Comment by Eluminae** [comment]
Ok, my bad. Path works relatively to the root dotfiles folder !

**Comment by Eluminae** [comment]
{%@@ include 'base16/qutebrowser/themes/' + color_scheme + '.config.py' @@%}
woks

**Comment by deadc0de6** [comment]
Yes templates will be relative to the root dotfiles directory as the jinja2 template engine is initialized with that directory.
Is it working for you or this is still an issue?

**Comment by Eluminae** [comment]
I think an absolute path should work anyway. But my problem is fixed with root relative paths.

**Comment by deadc0de6** [comment]
Jinja2 is only able to load (`include`) templates relatively to its context. Currently the context for jinja2 within dotdrop is the *dotpath*.

I see two solutions to having the ability to `include` templates from a different directory than the *dotpath*:

* add an option on the command line to *register* additional paths in jinja2 (like `--templatedir=<path>`)
* create a custom function that somehow would include an entire file from an absolute path (see [available methods](https://github.com/deadc0de6/dotdrop/wiki/templating#available-methods) and [jhelpers.py](https://github.com/deadc0de6/dotdrop/blob/master/dotdrop/jhelpers.py))

First solution is easy but not very elegant, the second solution (adding a function in [jhelpers.py](https://github.com/deadc0de6/dotdrop/blob/master/dotdrop/jhelpers.py)) is nice but I don't know if when doing that jinja2 would interpret the included template.
Still I wouldn't recommend to have templates outside the *dotpath*. Any specific reason you want to include templates outside of the *dotpath*?

ref:
* [jinja2 include](http://jinja.pocoo.org/docs/2.10/templates/#include)

**Comment by Eluminae** [comment]
Really good points. You right, use outside file inside dotfiles seems crazy.
Maybe leave the issue here if there is no really good reasons to do this.

**Comment by deadc0de6** [comment]
@Eluminae would you be ok for me to reference [your dotfiles](https://github.com/Eluminae/dotfiles) in the related doc section: <https://github.com/deadc0de6/dotdrop/wiki/people-using-dotdrop>

**Comment by Eluminae** [comment]
What a privilege. yes ofc you can :)

**Comment by deadc0de6** [comment]
:+1: thanks!

**Comment by Eluminae** [comment]
Thanks to you !
