### ISSUE TITLE
[bug] dotdrop compare failed on 0.29

### ISSUE THREAD

**Issue by laggardkernel** [deadc0de6/dotdrop#160]
Dotdrop version (and git commit if run from source): v0.29.1
Using dotdrop: as a submodule

**Describe the bug**

After running 

```bash
$HOME/.dotfiles/dotdrop.sh compare -Vb -c $HOME/.dotfiles/config.yaml -p Darwin
```

`TypeError: 'NoneType' object is not iterable` is thrown out.

```python
[DEBUG][__main__.main] running cmd: compare
Traceback (most recent call last):
  File "/Users/username/.local/share/pyenv/versions/3.6.8/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/username/.local/share/pyenv/versions/3.6.8/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/username/.dotfiles/dotdrop/dotdrop/dotdrop.py", line 649, in <module>
    if main():
  File "/Users/username/.dotfiles/dotdrop/dotdrop/dotdrop.py", line 610, in main
    ret = cmd_compare(o, tmp)
  File "/Users/username/.dotfiles/dotdrop/dotdrop/dotdrop.py", line 204, in cmd_compare
    debug=o.debug)
  File "/Users/username/.dotfiles/dotdrop/dotdrop/templategen.py", line 47, in __init__
    self.env.globals.update(variables)
TypeError: 'NoneType' object is not iterable
```

While, the same command worked well and did a complete diff on all dotfiles with dotdrop 0.28.

**Comment by deadc0de6** [comment]
Thanks for reporting this!
Should be fixed in the master branch.

**Comment by laggardkernel** [comment]
Thanks for such a quick fix. My problem is solved.
