### ISSUE TITLE
[bug] TypeError: sequence item 1: expected str instance, int found

### ISSUE THREAD

**Issue by mygithubthrowaway** [deadc0de6/dotdrop#167]
Dotdrop version 0.29.1
Archlinux

**Describe the bug**

Cant import new dotfiles

**Steps to Reproduce**

dotdrop import .some_dotfiles

**Expected behavior**

Normal import

**Additional information**

Dotdrop's execution without the debug logs (too many personal information to post on github)
```
Traceback (most recent call last):
  File "/usr/bin/dotdrop", line 11, in <module>
    load_entry_point('dotdrop==0.29.1', 'console_scripts', 'dotdrop')()
  File "/usr/lib/python3.7/site-packages/dotdrop/__init__.py", line 11, in main
    if dotdrop.dotdrop.main():
  File "/usr/lib/python3.7/site-packages/dotdrop/dotdrop.py", line 618, in main
    ret = cmd_importer(o)
  File "/usr/lib/python3.7/site-packages/dotdrop/dotdrop.py", line 374, in cmd_importer
    retconf = o.conf.new(src, dst, linktype, o.profile)
  File "/usr/lib/python3.7/site-packages/dotdrop/cfg_aggregator.py", line 159, in new
    key = self._get_new_dotfile_key(dst)
  File "/usr/lib/python3.7/site-packages/dotdrop/cfg_aggregator.py", line 185, in _get_new_dotfile_key
    return self._get_short_key(path, existing_keys)
  File "/usr/lib/python3.7/site-packages/dotdrop/cfg_aggregator.py", line 232, in _get_short_key
    return self._uniq_key(key, keys)
  File "/usr/lib/python3.7/site-packages/dotdrop/cfg_aggregator.py", line 241, in _uniq_key
    newkey = self.key_sep.join([key, cnt])
TypeError: sequence item 1: expected str instance, int found
...
```

**Comment by deadc0de6** [comment]
Thanks for reporting this, I have the feeling this is fixed in the master branch, did you install from aur? dotdrop? dotdrop-git?
Could you try with dotdrop's version from master?

**Comment by deadc0de6** [comment]
Could you also show parts of your config file as it could be something related to a yaml issue (or maybe a diff of what changed in your config)

**Comment by deadc0de6** [comment]
Ok sorry it was indeed a bug and I fixed it in above commit.

**Comment by mygithubthrowaway** [comment]
Can confirm: now works, thanks
