### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by ask1234560** [deadc0de6/dotdrop#225]
Dotdrop version : 1.0.0

This is my [dotfiles dotdrop repo](https://github.com/ask1234560/dotfiles_bspwm)

* I use pipenv for virtualisation
* I am trying to install the dotdrop repo in ubuntu server in google cloud
* getting this error
```
./dotdrop.sh  install
     _       _      _
  __| | ___ | |_ __| |_ __ ___  _ __
 / _` |/ _ \| __/ _` | '__/ _ \| '_ |
 \__,_|\___/ \__\__,_|_|  \___/| .__/  v1.0.0
                               |_|

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/.config/dotfiles_bspwm/dotdrop/dotdrop/dotdrop.py", line 716, in <module>
    if main():
  File "/root/.config/dotfiles_bspwm/dotdrop/dotdrop/dotdrop.py", line 670, in main
    ret = cmd_install(o)
  File "/root/.config/dotfiles_bspwm/dotdrop/dotdrop/dotdrop.py", line 144, in cmd_install
    r, err = inst.install(t, src, dotfile.dst,
  File "/root/.config/dotfiles_bspwm/dotdrop/dotdrop/installer.py", line 96, in install
    return self._handle_file(templater, src, dst,
  File "/root/.config/dotfiles_bspwm/dotdrop/dotdrop/installer.py", line 311, in _handle_file
    content = templater.generate(src)
  File "/root/.config/dotfiles_bspwm/dotdrop/dotdrop/templategen.py", line 75, in generate
    return self._handle_file(src)
  File "/root/.config/dotfiles_bspwm/dotdrop/dotdrop/templategen.py", line 122, in _handle_file
    _, filetype = utils.run(['file', '-b', src],
  File "/root/.config/dotfiles_bspwm/dotdrop/dotdrop/utils.py", line 35, in run
    p = subprocess.Popen(cmd, shell=False,
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'file'
``` 
* but i installed the same dotdrop repo in my host machine for a different user, then the error is not there

**Steps to Reproduce**

1. cd ~/.config
2. git clone https://github.com/ask1234560/dotfiles_bspwm
3. cd dotfiles_bspwm
4. git submodule init 
5. git submodule update --recursive
6. pipenv sync
7. pipenv shell
8. cp config.yaml config.yaml.bak
9. substitute hostname
    * awk '{gsub(/arch/,"hostname")} {print $0}' config.yaml.bak | tee config.yaml
10. ./dotdrop.sh install

**Expected behavior**

All the dotfiles in ```~/.config/dotfiles_bspwm```  are copied to their places

**Additional information**

The relevant part of the config file
```yaml
config:
  backup: true
  create: true
  dotpath: dotfiles
  instignore:
  - '*/README.md'
  upignore:
  - '*/README.md'
dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
profiles:
  ubuntu-docker:
    dotfiles:
    - f_zshrc
```

Dotdrop's execution with the debug logs (`--verbose`)
```bash
$ ./dotdrop.sh install --verbose
[DEBUG][dotdrop.options.__init__] version: 1.0.0
[DEBUG][dotdrop.options.__init__] config file: config.yaml
[DEBUG][dotdrop.cfg_yaml._norm_path] normalizing path dotfiles
[DEBUG][dotdrop.cfg_yaml._norm_path] normalizing path dotfiles relative to config file directory
[DEBUG][dotdrop.cfg_yaml._norm_path] normalizing path ~/.config/dotdrop
[DEBUG][dotdrop.cfg_yaml._parse_main_yaml] settings: {'backup': True, 'banner': True, 'create': True, 'dotpath': '/root/.config/dotfiles_bspwm/dotfiles', 'ignoreempty': True, 'keepdot': False, 'link_dotfile_default': 'nolink', 'link_on_import': 'nolink', 'longkey': False, 'showdiff': False, 'workdir': '/root/.config/dotdrop', 'minversion': None, 'diff_command': 'diff -r -u {0} {1}', 'default_actions': [], 'import_actions': [], 'import_configs': [], 'import_variables': [], 'cmpignore': [], 'upignore': ['*/README.md'], 'instignore': ['*/README.md'], 'func_file': [], 'filter_file': []}
[DEBUG][dotdrop.cfg_yaml._parse_main_yaml] dotfiles: {'f_zshrc': ordereddict([('src', 'zshrc'), ('dst', '~/.zshrc'), ('link', 'nolink'), ('ignoreempty', True)])}
[DEBUG][dotdrop.cfg_yaml._parse_main_yaml] profiles: {'ubuntu-docker': ordereddict([('dotfiles', ['f_zshrc'])])}
[DEBUG][dotdrop.cfg_yaml._parse_main_yaml] actions: {}
[DEBUG][dotdrop.cfg_yaml._parse_main_yaml] trans_r: {}
[DEBUG][dotdrop.cfg_yaml._parse_main_yaml] trans_w: {}
[DEBUG][dotdrop.cfg_yaml._parse_main_yaml] variables: {}
[DEBUG][dotdrop.cfg_yaml._parse_main_yaml] dynvariables: {}
[DEBUG][dotdrop.cfg_yaml.__init__] before normalization: ordereddict([('config', ordereddict([('backup', True), ('create', True), ('dotpath', 'dotfiles'), ('instignore', ['*/README.md']), ('upignore', ['*/README.md'])])), ('dotfiles', ordereddict([('f_zshrc', ordereddict([('src', 'zshrc'), ('dst', '~/.zshrc')]))])), ('profiles', ordereddict([('ubuntu-docker', ordereddict([('dotfiles', ['f_zshrc'])]))])), ('actions', {}), ('trans_read', {}), ('trans_write', {}), ('variables', {}), ('dynvariables', {})])
[DEBUG][dotdrop.cfg_yaml._merge_variables] get local variables
[DEBUG][dotdrop.cfg_yaml._norm_path] normalizing path /root/.config/dotfiles_bspwm/dotfiles
[DEBUG][dotdrop.cfg_yaml._norm_path] normalizing path /root/.config/dotfiles_bspwm/config.yaml
[DEBUG][dotdrop.cfg_yaml._norm_path] normalizing path /root/.config/dotdrop
[DEBUG][dotdrop.cfg_yaml._norm_path] normalizing path /root/.config/dotfiles_bspwm/dotfiles
[DEBUG][dotdrop.cfg_yaml._norm_path] normalizing path /root/.config/dotfiles_bspwm/config.yaml
[DEBUG][dotdrop.cfg_yaml._norm_path] normalizing path /root/.config/dotdrop
[DEBUG][dotdrop.cfg_yaml._debug_vars] variables:
[DEBUG][dotdrop.cfg_yaml._debug_vars] 	"profile": ubuntu-docker
[DEBUG][dotdrop.cfg_yaml._debug_vars] 	"_dotdrop_dotpath": /root/.config/dotfiles_bspwm/dotfiles
[DEBUG][dotdrop.cfg_yaml._debug_vars] 	"_dotdrop_cfgpath": /root/.config/dotfiles_bspwm/config.yaml
[DEBUG][dotdrop.cfg_yaml._debug_vars] 	"_dotdrop_workdir": /root/.config/dotdrop
[DEBUG][dotdrop.cfg_yaml._merge_variables] local variables resolved
[DEBUG][dotdrop.cfg_yaml._debug_vars] variables:
[DEBUG][dotdrop.cfg_yaml._debug_vars] 	"profile": ubuntu-docker
[DEBUG][dotdrop.cfg_yaml._debug_vars] 	"_dotdrop_dotpath": /root/.config/dotfiles_bspwm/dotfiles
[DEBUG][dotdrop.cfg_yaml._debug_vars] 	"_dotdrop_cfgpath": /root/.config/dotfiles_bspwm/config.yaml
[DEBUG][dotdrop.cfg_yaml._debug_vars] 	"_dotdrop_workdir": /root/.config/dotdrop
[DEBUG][dotdrop.cfg_yaml._norm_path] normalizing path /root/.config/dotfiles_bspwm/dotfiles
[DEBUG][dotdrop.cfg_yaml._norm_path] normalizing path /root/.config/dotfiles_bspwm/config.yaml
[DEBUG][dotdrop.cfg_yaml._norm_path] normalizing path /root/.config/dotdrop
[DEBUG][dotdrop.cfg_yaml._merge_variables] resolve all uses of variables in config
[DEBUG][dotdrop.cfg_yaml._debug_vars] variables:
[DEBUG][dotdrop.cfg_yaml._debug_vars] 	"profile": ubuntu-docker
[DEBUG][dotdrop.cfg_yaml._debug_vars] 	"_dotdrop_dotpath": /root/.config/dotfiles_bspwm/dotfiles
[DEBUG][dotdrop.cfg_yaml._debug_vars] 	"_dotdrop_cfgpath": /root/.config/dotfiles_bspwm/config.yaml
[DEBUG][dotdrop.cfg_yaml._debug_vars] 	"_dotdrop_workdir": /root/.config/dotdrop
[DEBUG][dotdrop.cfg_yaml._norm_path] normalizing path /root/.config/dotfiles_bspwm/dotfiles/zshrc
[DEBUG][dotdrop.cfg_yaml._norm_path] normalizing path ~/.zshrc
[DEBUG][dotdrop.cfg_yaml.__init__] after normalization: ordereddict([('config', ordereddict([('backup', True), ('create', True), ('dotpath', 'dotfiles'), ('instignore', ['*/README.md']), ('upignore', ['*/README.md'])])), ('dotfiles', ordereddict([('f_zshrc', ordereddict([('src', 'zshrc'), ('dst', '~/.zshrc')]))])), ('profiles', ordereddict([('ubuntu-docker', ordereddict([('dotfiles', ['f_zshrc'])]))])), ('actions', {}), ('trans_read', {}), ('trans_write', {}), ('variables', {}), ('dynvariables', {})])
[DEBUG][dotdrop.cfg_aggregator._load] settings: <dotdrop.settings.Settings object at 0x7f7240d2f9d0>
[DEBUG][dotdrop.cfg_aggregator._load] dotfiles: [dotfile(key:"f_zshrc", src:"/root/.config/dotfiles_bspwm/dotfiles/zshrc", dst:"/root/.zshrc", link:"nolink")]
[DEBUG][dotdrop.cfg_aggregator._load] profiles: [profile(key:"ubuntu-docker")]
[DEBUG][dotdrop.cfg_aggregator._load] actions: []
[DEBUG][dotdrop.cfg_aggregator._load] trans_r: []
[DEBUG][dotdrop.cfg_aggregator._load] trans_w: []
[DEBUG][dotdrop.cfg_aggregator._load] variables: {'profile': 'ubuntu-docker', '_dotdrop_dotpath': '/root/.config/dotfiles_bspwm/dotfiles', '_dotdrop_cfgpath': '/root/.config/dotfiles_bspwm/config.yaml', '_dotdrop_workdir': '/root/.config/dotdrop'}
[DEBUG][dotdrop.cfg_aggregator._patch_keys_to_objs] patching dotfiles ...
[DEBUG][dotdrop.cfg_aggregator._patch_keys_to_objs] patching key:"ubuntu-docker".dotfiles with [dotfile(key:"f_zshrc", src:"/root/.config/dotfiles_bspwm/dotfiles/zshrc", dst:"/root/.zshrc", link:"nolink")]
[DEBUG][dotdrop.cfg_aggregator._patch_keys_to_objs] patching actions ...
[DEBUG][dotdrop.cfg_aggregator._patch_keys_to_objs] patching actions ...
[DEBUG][dotdrop.cfg_aggregator._patch_keys_to_objs] patching default_actions ...
[DEBUG][dotdrop.cfg_aggregator._load] default actions: []
[DEBUG][dotdrop.cfg_aggregator._patch_keys_to_objs] patching trans_r ...
[DEBUG][dotdrop.cfg_aggregator._patch_keys_to_objs] patching trans_w ...
[DEBUG][dotdrop.options._read_config] new setting: backup=True
[DEBUG][dotdrop.options._read_config] new setting: banner=True
[DEBUG][dotdrop.options._read_config] new setting: create=True
[DEBUG][dotdrop.options._read_config] new setting: dotpath=/root/.config/dotfiles_bspwm/dotfiles
[DEBUG][dotdrop.options._read_config] new setting: ignoreempty=True
[DEBUG][dotdrop.options._read_config] new setting: keepdot=False
[DEBUG][dotdrop.options._read_config] new setting: link_dotfile_default=nolink
[DEBUG][dotdrop.options._read_config] new setting: link_on_import=nolink
[DEBUG][dotdrop.options._read_config] new setting: longkey=False
[DEBUG][dotdrop.options._read_config] new setting: showdiff=False
[DEBUG][dotdrop.options._read_config] new setting: workdir=/root/.config/dotdrop
[DEBUG][dotdrop.options._read_config] new setting: minversion=None
[DEBUG][dotdrop.options._read_config] new setting: diff_command=diff -r -u {0} {1}
[DEBUG][dotdrop.options._read_config] new setting: default_actions=[]
[DEBUG][dotdrop.options._read_config] new setting: import_actions=[]
[DEBUG][dotdrop.options._read_config] new setting: import_configs=[]
[DEBUG][dotdrop.options._read_config] new setting: import_variables=[]
[DEBUG][dotdrop.options._read_config] new setting: cmpignore=[]
[DEBUG][dotdrop.options._read_config] new setting: upignore=['*/README.md']
[DEBUG][dotdrop.options._read_config] new setting: instignore=['*/README.md']
[DEBUG][dotdrop.options._read_config] new setting: func_file=[]
[DEBUG][dotdrop.options._read_config] new setting: filter_file=[]
     _       _      _
  __| | ___ | |_ __| |_ __ ___  _ __
 / _` |/ _ \| __/ _` | '__/ _ \| '_ |
 \__,_|\___/ \__\__,_|_|  \___/| .__/  v1.0.0
                               |_|

[DEBUG][dotdrop.options._debug_attr] CLI options:
[DEBUG][dotdrop.options._debug_attr] - args: {'--as': None,
 '--cfg': None,
 '--dry': False,
 '--file': [],
 '--force': False,
 '--force-actions': False,
 '--grepable': False,
 '--help': False,
 '--ignore': ['*.dotdropbak', '*/README.md', '*.dotdropbak'],
 '--key': False,
 '--link': None,
 '--no-banner': False,
 '--nodiff': False,
 '--profile': 'ubuntu-docker',
 '--show-patch': False,
 '--showdiff': False,
 '--temp': False,
 '--template': False,
 '--verbose': True,
 '--version': False,
 '<key>': [],
 '<path>': [],
 'compare': False,
 'detail': False,
 'files': False,
 'import': False,
 'install': True,
 'profiles': False,
 'remove': False,
 'update': False}
[DEBUG][dotdrop.options._debug_attr] - backup: True
[DEBUG][dotdrop.options._debug_attr] - banner: True
[DEBUG][dotdrop.options._debug_attr] - cmd_compare: False
[DEBUG][dotdrop.options._debug_attr] - cmd_detail: False
[DEBUG][dotdrop.options._debug_attr] - cmd_files: False
[DEBUG][dotdrop.options._debug_attr] - cmd_import: False
[DEBUG][dotdrop.options._debug_attr] - cmd_install: True
[DEBUG][dotdrop.options._debug_attr] - cmd_profiles: False
[DEBUG][dotdrop.options._debug_attr] - cmd_remove: False
[DEBUG][dotdrop.options._debug_attr] - cmd_update: False
[DEBUG][dotdrop.options._debug_attr] - cmpignore: []
[DEBUG][dotdrop.options._debug_attr] - compare_focus: []
[DEBUG][dotdrop.options._debug_attr] - compare_ignore: ['*.dotdropbak']
[DEBUG][dotdrop.options._debug_attr] - conf: <dotdrop.cfg_aggregator.CfgAggregator object at 0x7f7241927bb0>
[DEBUG][dotdrop.options._debug_attr] - confpath: config.yaml
[DEBUG][dotdrop.options._debug_attr] - create: True
[DEBUG][dotdrop.options._debug_attr] - debug: True
[DEBUG][dotdrop.options._debug_attr] - default_actions: []
[DEBUG][dotdrop.options._debug_attr] - detail_keys: []
[DEBUG][dotdrop.options._debug_attr] - diff_command: diff -r -u {0} {1}
[DEBUG][dotdrop.options._debug_attr] - dotfiles: [dotfile(key:"f_zshrc", src:"/root/.config/dotfiles_bspwm/dotfiles/zshrc", dst:"/root/.zshrc", link:"nolink")]
[DEBUG][dotdrop.options._debug_attr] - dotpath: /root/.config/dotfiles_bspwm/dotfiles
[DEBUG][dotdrop.options._debug_attr] - dry: False
[DEBUG][dotdrop.options._debug_attr] - files_grepable: False
[DEBUG][dotdrop.options._debug_attr] - files_templateonly: False
[DEBUG][dotdrop.options._debug_attr] - filter_file: []
[DEBUG][dotdrop.options._debug_attr] - func_file: []
[DEBUG][dotdrop.options._debug_attr] - ignoreempty: True
[DEBUG][dotdrop.options._debug_attr] - import_actions: []
[DEBUG][dotdrop.options._debug_attr] - import_as: None
[DEBUG][dotdrop.options._debug_attr] - import_configs: []
[DEBUG][dotdrop.options._debug_attr] - import_link: nolink
[DEBUG][dotdrop.options._debug_attr] - import_path: []
[DEBUG][dotdrop.options._debug_attr] - import_variables: []
[DEBUG][dotdrop.options._debug_attr] - install_backup_suffix: .dotdropbak
[DEBUG][dotdrop.options._debug_attr] - install_default_actions_post: []
[DEBUG][dotdrop.options._debug_attr] - install_default_actions_pre: []
[DEBUG][dotdrop.options._debug_attr] - install_diff: True
[DEBUG][dotdrop.options._debug_attr] - install_force_action: False
[DEBUG][dotdrop.options._debug_attr] - install_ignore: ['*/README.md']
[DEBUG][dotdrop.options._debug_attr] - install_keys: []
[DEBUG][dotdrop.options._debug_attr] - install_showdiff: False
[DEBUG][dotdrop.options._debug_attr] - install_temporary: False
[DEBUG][dotdrop.options._debug_attr] - instignore: ['*/README.md']
[DEBUG][dotdrop.options._debug_attr] - keepdot: False
[DEBUG][dotdrop.options._debug_attr] - link_dotfile_default: nolink
[DEBUG][dotdrop.options._debug_attr] - link_on_import: nolink
[DEBUG][dotdrop.options._debug_attr] - log: <dotdrop.logger.Logger object at 0x7f7241859cd0>
[DEBUG][dotdrop.options._debug_attr] - longkey: False
[DEBUG][dotdrop.options._debug_attr] - minversion: None
[DEBUG][dotdrop.options._debug_attr] - profile: ubuntu-docker
[DEBUG][dotdrop.options._debug_attr] - profiles: [profile(key:"ubuntu-docker")]
[DEBUG][dotdrop.options._debug_attr] - profiles_grepable: False
[DEBUG][dotdrop.options._debug_attr] - remove_iskey: False
[DEBUG][dotdrop.options._debug_attr] - remove_path: []
[DEBUG][dotdrop.options._debug_attr] - safe: True
[DEBUG][dotdrop.options._debug_attr] - showdiff: False
[DEBUG][dotdrop.options._debug_attr] - update_ignore: ['*.dotdropbak', '*/README.md']
[DEBUG][dotdrop.options._debug_attr] - update_iskey: False
[DEBUG][dotdrop.options._debug_attr] - update_path: []
[DEBUG][dotdrop.options._debug_attr] - update_showpatch: False
[DEBUG][dotdrop.options._debug_attr] - upignore: ['*/README.md']
[DEBUG][dotdrop.options._debug_attr] - variables: {'profile': 'ubuntu-docker', '_dotdrop_dotpath': '/root/.config/dotfiles_bspwm/dotfiles', '_dotdrop_cfgpath': '/root/.config/dotfiles_bspwm/config.yaml', '_dotdrop_workdir': '/root/.config/dotdrop'}
[DEBUG][dotdrop.options._debug_attr] - workdir: /root/.config/dotdrop
[DEBUG][__main__.main]


[DEBUG][__main__.main] running cmd: install
[DEBUG][dotdrop.templategen.__init__] load global functions:
[DEBUG][dotdrop.templategen._load_funcs_to_dic] load function "basename"
[DEBUG][dotdrop.templategen._load_funcs_to_dic] load function "dirname"
[DEBUG][dotdrop.templategen._load_funcs_to_dic] load function "exists"
[DEBUG][dotdrop.templategen._load_funcs_to_dic] load function "exists_in_path"
[DEBUG][dotdrop.templategen.__init__] template additional variables: {'profile': 'ubuntu-docker', '_dotdrop_dotpath': '/root/.config/dotfiles_bspwm/dotfiles', '_dotdrop_cfgpath': '/root/.config/dotfiles_bspwm/config.yaml', '_dotdrop_workdir': '/root/.config/dotdrop'}
[DEBUG][__main__.cmd_install] execute profile pre actions
[DEBUG][__main__.cmd_install] installing key:"f_zshrc", src:"/root/.config/dotfiles_bspwm/dotfiles/zshrc", dst:"/root/.zshrc", link:"nolink"
[DEBUG][dotdrop.utils.patch_ignores] ignores before patching: ['*/README.md']
[DEBUG][dotdrop.utils.patch_ignores] ignores after patching: ['*/README.md']
[DEBUG][dotdrop.installer.install] install "/root/.config/dotfiles_bspwm/dotfiles/zshrc" to "/root/.zshrc"
[DEBUG][dotdrop.installer.install] install /root/.config/dotfiles_bspwm/dotfiles/zshrc to /root/.zshrc
[DEBUG][dotdrop.installer.install] is "/root/.config/dotfiles_bspwm/dotfiles/zshrc" a directory: False
[DEBUG][dotdrop.installer._handle_file] generate template for /root/.config/dotfiles_bspwm/dotfiles/zshrc
[DEBUG][dotdrop.installer._handle_file] ignore empty: True
[DEBUG][dotdrop.installer._handle_file] ignore pattern: ['*/README.md']
[DEBUG][dotdrop.utils.must_ignore] must ignore? ['/root/.config/dotfiles_bspwm/dotfiles/zshrc', '/root/.zshrc'] against ['*/README.md']
[DEBUG][dotdrop.utils.run] exec: file -b /root/.config/dotfiles_bspwm/dotfiles/zshrc
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/.config/dotfiles_bspwm/dotdrop/dotdrop/dotdrop.py", line 716, in <module>
    if main():
  File "/root/.config/dotfiles_bspwm/dotdrop/dotdrop/dotdrop.py", line 670, in main
    ret = cmd_install(o)
  File "/root/.config/dotfiles_bspwm/dotdrop/dotdrop/dotdrop.py", line 144, in cmd_install
    r, err = inst.install(t, src, dotfile.dst,
  File "/root/.config/dotfiles_bspwm/dotdrop/dotdrop/installer.py", line 96, in install
    return self._handle_file(templater, src, dst,
  File "/root/.config/dotfiles_bspwm/dotdrop/dotdrop/installer.py", line 311, in _handle_file
    content = templater.generate(src)
  File "/root/.config/dotfiles_bspwm/dotdrop/dotdrop/templategen.py", line 75, in generate
    return self._handle_file(src)
  File "/root/.config/dotfiles_bspwm/dotdrop/dotdrop/templategen.py", line 122, in _handle_file
    _, filetype = utils.run(['file', '-b', src],
  File "/root/.config/dotfiles_bspwm/dotdrop/dotdrop/utils.py", line 35, in run
    p = subprocess.Popen(cmd, shell=False,
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'file'
...
```

Any additional information that would help reproduce the bug.

```
pipenv --version
pipenv, version 2018.11.26
```
```
 pip3 -V
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
```

host machine is arch linux and the error is showing in 
```
cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

```
cat Pipfile
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
docopt = "*"
Jinja2 = "*"
"ruamel.yaml" = "*"

[requires]
python_version = "3.8"


```
```
python -V
Python 3.8.2

```

**Comment by deadc0de6** [comment]
Thanks for reporting this. Dotdrop uses the tool [file](https://manpages.ubuntu.com/manpages/bionic/man1/file.1.html) to identify the type of files it is dealing with however it looks as if the host on which you are running dotdrop doesn't have it.

Can you try `which file` or similar to confirm? Also is it in the `PATH`?

**Comment by ask1234560** [comment]
Thank you it fixed, the server is so minimal that it doesn't have these basic stuffs. Wasted my hours for fixing it, if possible add __file__ as some dependency in docs. And once again thank you for replying fast and creating the tool

**Comment by deadc0de6** [comment]
It was already in the dependencies doc actually (see [here](https://github.com/deadc0de6/dotdrop/wiki/dependencies)) however I agree, we are so used to have these tools available that we forget about them.
You're welcome, happy dotdrop helps!

**Comment by deadc0de6** [comment]
@ask1234560 I added a checks when dotdrop starts to make sure all needed tools are available in the PATH and it should return something like below if dependencies are not met:
```
[ERR] tool "file" was not found in the PATH!
```

**Comment by ask1234560** [comment]
Great
