### ISSUE TITLE
[bug] problems with link_children

### ISSUE THREAD

**Issue by josaladino2** [deadc0de6/dotdrop#265]
Dotdrop version (and git commit if run from source): v0.xxx
Using dotdrop: as a submodule, from pypi, '...'
v 1.2.1
**Describe the bug**
dotdrop import --link="link_children" ~/.emacs.d
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/joe/dotfiles/dotdrop/dotdrop/dotdrop.py", line 747, in <module>
    if main():
  File "/Users/joe/dotfiles/dotdrop/dotdrop/dotdrop.py", line 664, in main
    o = Options()
  File "/Users/joe/dotfiles/dotdrop/dotdrop/options.py", line 130, in __init__
    self._read_config()
  File "/Users/joe/dotfiles/dotdrop/dotdrop/options.py", line 187, in _read_config
    self.conf = Cfg(self.confpath, self.profile, debug=self.debug,
  File "/Users/joe/dotfiles/dotdrop/dotdrop/cfg_aggregator.py", line 44, in __init__
    self._load()
  File "/Users/joe/dotfiles/dotdrop/dotdrop/cfg_aggregator.py", line 53, in _load
    self.settings = Settings.parse(None, self.cfgyaml.settings)
  File "/Users/joe/dotfiles/dotdrop/dotdrop/dictparser.py", line 30, in parse
    return cls(**newv)
TypeError: __init__() got an unexpected keyword argument 'link_children'
Not sure, I did dotdrop import --link=link_children ~/.emacs.d (a directory) and got the above errors
**Steps to Reproduce**
dotdrop import --link="link_children" ~/.emacs.d
1. Create a dotfile with content '...'
2. '...'

**Expected behavior**
expected to have all the files in that folder imported and then symbolic linked when I ran dotdrop install

**Additional information**

The relevant part of the config file
```yaml
config file content
```
Nothing is getting into the config file.  Crashes before it can
Dotdrop's execution with the debug logs (`--verbose`)
```bash
I am running zsh
$ dotdrop <cmd> --verbose ...
...
```

Any additional information that would help reproduce the bug.
Thanks.

**Comment by deadc0de6** [comment]
Thanks for reporting this, I'm however unable to reproduce this bug.

This sounds like there's some issues in your config file but without it I'm unable to help.

Can you provide me with following information:

* how's dotdrop is installed (submodule, pypi, etc)
* python version (I'm guessing 3.8.5)
* your `config.yaml` content
* a run of the command with `--verbose` to get more logs
