### ISSUE TITLE
[bug] if configuration file cannot be found yaml parser tries to read current directory

### ISSUE THREAD

**Issue by scrool** [deadc0de6/dotdrop#287]
Dotdrop version (and git commit if run from source): v1.3.6
Using dotdrop: pypi

**Describe the bug**

If configuration file is not found in any location candidates, config parser tries to read current directory as a configuration file which obviously fails.

**Steps to Reproduce**

1. Install dotdrop from pip `pip install --user dotdrop`
2. Run any command that reads configuration file, e.g. `dotdrop profiles`
3. If `$CWD` is `/` you get:
```
[ERR] [Errno 21] Is a directory: '/' 
[ERR] config error: config yaml error: / 
```

**Expected behavior**

An error message stating that configuration file was not found before configuration file is attempted to be read.

**Additional information**

Dotdrop's execution with the debug logs (`--verbose`)
```bash
$ dotdrop --verbose profiles
[DEBUG][dotdrop.options.__init__] version: 1.3.6
[DEBUG][dotdrop.options.__init__] command: /home/user/.local/bin/dotdrop --verbose profiles
[DEBUG][dotdrop.options.__init__] config file: 
[DEBUG][dotdrop.cfg_yaml._dbg] [] ----------start:/----------
Traceback (most recent call last):
  File "/home/user/.local/bin/dotdrop", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.8/site-packages/dotdrop/__init__.py", line 11, in main
    if dotdrop.dotdrop.main():
  File "/home/user/.local/lib/python3.8/site-packages/dotdrop/dotdrop.py", line 685, in main
    o = Options()
  File "/home/user/.local/lib/python3.8/site-packages/dotdrop/options.py", line 131, in __init__
    self._read_config()
  File "/home/user/.local/lib/python3.8/site-packages/dotdrop/options.py", line 188, in _read_config
    self.conf = Cfg(self.confpath, self.profile, debug=self.debug,
  File "/home/user/.local/lib/python3.8/site-packages/dotdrop/cfg_aggregator.py", line 44, in __init__
    self._load()
  File "/home/user/.local/lib/python3.8/site-packages/dotdrop/cfg_aggregator.py", line 48, in _load
    self.cfgyaml = CfgYaml(self.path,
  File "/home/user/.local/lib/python3.8/site-packages/dotdrop/cfg_yaml.py", line 133, in __init__
    self._yaml_dict = self._load_yaml(self._path)
  File "/home/user/.local/lib/python3.8/site-packages/dotdrop/cfg_yaml.py", line 1020, in _load_yaml
    with open(path, 'r') as f:
IsADirectoryError: [Errno 21] Is a directory: '/'
```

**Comment by deadc0de6** [comment]
Thanks for reporting this! The above fix will be part of the next release.

**Comment by deadc0de6** [comment]
@scrool new version 1.3.7 released with above fix.
