### ISSUE TITLE
[bug] AttributeError: module 'magic' has no attribute 'from_file'

### ISSUE THREAD

**Issue by dbankmann** [deadc0de6/dotdrop#289]
Dotdrop version (and git commit if run from source): v1.3.7 and auto-updated commit
Using dotdrop: as a submodule

**Describe the bug**

See title.

**Steps to Reproduce**

Run dotdrop install with templates.

**Additional information**
I can add more information if necessary, but for now  it seems obvious to me, since the module magic indeed does not have this attribute.

```bash
DOTDROP_AUTOUPDATE=no dotdrop install
     _       _      _
  __| | ___ | |_ __| |_ __ ___  _ __
 / _` |/ _ \| __/ _` | '__/ _ \| '_ |
 \__,_|\___/ \__\__,_|_|  \___/| .__/  v1.3.7
                               |_|

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/daniel/dotfiles/dotdrop/dotdrop/dotdrop.py", line 782, in <module>
    if main():
  File "/home/daniel/dotfiles/dotdrop/dotdrop/dotdrop.py", line 731, in main
    ret = cmd_install(o)
  File "/home/daniel/dotfiles/dotdrop/dotdrop/dotdrop.py", line 149, in cmd_install
    r, err = inst.install(t, src, dotfile.dst,
  File "/home/daniel/dotfiles/dotdrop/dotdrop/installer.py", line 113, in install
    b, e = self._install_file(templater, src, dst,
  File "/home/daniel/dotfiles/dotdrop/dotdrop/installer.py", line 350, in _install_file
    content = templater.generate(src)
  File "/home/daniel/dotfiles/dotdrop/dotdrop/templategen.py", line 91, in generate
    return self._handle_file(src)
  File "/home/daniel/dotfiles/dotdrop/dotdrop/templategen.py", line 151, in _handle_file
    filetype = magic.from_file(src, mime=True)
AttributeError: module 'magic' has no attribute 'from_file'

...
```

**Comment by deadc0de6** [comment]
Dotdrop now depends on [python-magic from pypi](https://pypi.org/project/python-magic/) which has the `from_file` attribute. It seems you have another module called magic which is wrongly imported by dotdrop instead of `python-magic`, do you know which one? 

Could you run `pip freeze | grep -i magic` to find out maybe?

**Comment by dbankmann** [comment]
Okay, got it. I installed the arch package `python-magic` which surprisingly are the python bindings from  https://github.com/file/file and _not_ the `python-magic` package from pypi.
