### ISSUE TITLE
Install doesn't create directories for symlinks

### ISSUE THREAD

**Issue by lyze237** [deadc0de6/dotdrop#30]
Hello!

I get the following crash when I tried to install my dotfiles on a new machine:

```bash
~/t/dotfiles OvO/"/ ./dotdrop.sh install                                                                                                        master\"\^v^/"/?+
     _       _      _
  __| | ___ | |_ __| |_ __ ___  _ __
 / _` |/ _ \| __/ _` | '__/ _ \| '_ |
 \__,_|\___/ \__\__,_|_|  \___/| .__/  v0.10.4
                               |_|

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/wml/tmp/dotfiles/dotdrop/dotdrop/dotdrop.py", line 346, in <module>
    if main():
  File "/Users/wml/tmp/dotfiles/dotdrop/dotdrop/dotdrop.py", line 318, in main
    ret = install(opts, conf)
  File "/Users/wml/tmp/dotfiles/dotdrop/dotdrop/dotdrop.py", line 90, in install
    r = inst.link(dotfile.src, dotfile.dst)
  File "/Users/wml/tmp/dotfiles/dotdrop/dotdrop/installer.py", line 62, in link
    os.symlink(src, dst)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/wml/tmp/dotfiles/dotfiles/tmp/config/test' -> '/Users/wml/tmp/config/test'
~/t/dotfiles OvO/"/ ./dotdrop.sh install --dry                                                                                                  master\"\^v^/"/?+
     _       _      _
  __| | ___ | |_ __| |_ __ ___  _ __
 / _` |/ _ \| __/ _` | '__/ _ \| '_ |
 \__,_|\___/ \__\__,_|_|  \___/| .__/  v0.10.4
                               |_|

[DRY] would link /Users/wml/tmp/config/test to /Users/wml/tmp/dotfiles/dotfiles/tmp/config/test 

0 dotfile(s) installed.
```

Here's the way I did it:

```bash
~ OvO/"/ mkdir ~/tmp
~ OvO/"/ cd ~/tmp
~/tmp OvO/"/ mkdir dotfiles
~/tmp OvO/"/ cd dotfiles/
~/t/dotfiles OvO/"/ git init
Initialized empty Git repository in /Users/wml/tmp/dotfiles/.git/
~/t/dotfiles OvO/"/ git submodule add https://github.com/deadc0de6/dotdrop.git                                                                       master\"\^v^
Cloning into '/Users/wml/tmp/dotfiles/dotdrop'...
remote: Counting objects: 954, done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 954 (delta 29), reused 30 (delta 14), pack-reused 898
Receiving objects: 100% (954/954), 184.85 KiB | 267.00 KiB/s, done.
Resolving deltas: 100% (621/621), done.
~/t/dotfiles OvO/"/ ./dotdrop/bootstrap.sh                                                                                                       master\"\^v^/"/+
~/t/dotfiles OvO/"/ mkdir ../config                                                                                                             master\"\^v^/"/?+
~/t/dotfiles OvO/"/ echo hi > ../config/test                                                                                                    master\"\^v^/"/?+
~/t/dotfiles OvO/"/ ./dotdrop.sh import -l ~/tmp/config/test                                                                                    master\"\^v^/"/?+
     _       _      _
  __| | ___ | |_ __| |_ __ ___  _ __
 / _` |/ _ \| __/ _` | '__/ _ \| '_ |
 \__,_|\___/ \__\__,_|_|  \___/| .__/  v0.10.4
                               |_|

        -> "/Users/wml/tmp/config/test" imported

1 file(s) imported.
~/t/dotfiles OvO/"/ rm -r ../config   #simulate new install                                                                         master\"\^v^/"/?+
~/t/dotfiles OvO/"/ ./dotdrop.sh install                                                                                                        master\"\^v^/"/?+
     _       _      _
  __| | ___ | |_ __| |_ __ ___  _ __
 / _` |/ _ \| __/ _` | '__/ _ \| '_ |
 \__,_|\___/ \__\__,_|_|  \___/| .__/  v0.10.4
                               |_|

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/wml/tmp/dotfiles/dotdrop/dotdrop/dotdrop.py", line 346, in <module>
    if main():
  File "/Users/wml/tmp/dotfiles/dotdrop/dotdrop/dotdrop.py", line 318, in main
    ret = install(opts, conf)
  File "/Users/wml/tmp/dotfiles/dotdrop/dotdrop/dotdrop.py", line 90, in install
    r = inst.link(dotfile.src, dotfile.dst)
  File "/Users/wml/tmp/dotfiles/dotdrop/dotdrop/installer.py", line 62, in link
    os.symlink(src, dst)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/wml/tmp/dotfiles/dotfiles/tmp/config/test' -> '/Users/wml/tmp/config/test'
```

And here's the test yaml it generated:

```yaml
~/t/dotfiles OvO/"/ cat config.yaml                                                                                                             master\"\^v^/"/?+
config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_test:
    dst: ~/tmp/config/test
    link: true
    src: tmp/config/test
profiles:
  3dboyss-MBP:
    dotfiles:
    - f_test
```

I tried it with: antergos, macos high sierra

---

Here's the line where it crashes: https://github.com/deadc0de6/dotdrop/blob/master/dotdrop/installer.py#L62

```python
        if self.dry:
            self.log.dry('would link %s to %s' % (dst, src))
            return []
        os.symlink(src, dst)
        self.log.sub('linked %s to %s' % (dst, src))
```

**Comment by lyze237** [comment]
pr got accepted.
