### ISSUE TITLE
[bug] Impignore option causes Dotdrop to crash.

### ISSUE THREAD

**Issue by molguin92** [deadc0de6/dotdrop#316]
Dotdrop version: v1.5.4
Using dotdrop: As git submodule.

`impignore` option in `config.yaml` causes dotdrop to crash.

**Steps to Reproduce**

1. Edit `config.yaml` to include the `impignore` option under some dotfile directory, e.g.:

```yaml
d_vim:
  src: vim
  dst: ~/.vim
  impignore:
    - "bundle/*"
```
2. Activate the dotdrop Pyhon virtual environment (in my case using `virtualenvwrapper`: `workon dotdrop`; python version 3.9.6).
3. Run `dotdrop update`.
4. Receive a type error from Python:

```console
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/molguin/dotfiles/dotdrop/dotdrop/dotdrop.py", line 848, in <module>
    if main():
  File "/home/molguin/dotfiles/dotdrop/dotdrop/dotdrop.py", line 819, in main
    opts = Options()
  File "/home/molguin/dotfiles/dotdrop/dotdrop/options.py", line 157, in __init__
    self._read_config()
  File "/home/molguin/dotfiles/dotdrop/dotdrop/options.py", line 219, in _read_config
    self.conf = Cfg(self.confpath, self.profile, debug=self.debug,
  File "/home/molguin/dotfiles/dotdrop/dotdrop/cfg_aggregator.py", line 45, in __init__
    self._load()
  File "/home/molguin/dotfiles/dotdrop/dotdrop/cfg_aggregator.py", line 219, in _load
    self.dotfiles = Dotfile.parse_dict(self.cfgyaml.dotfiles)
  File "/home/molguin/dotfiles/dotdrop/dotdrop/dictparser.py", line 39, in parse_dict
    return [cls.parse(k, v) for k, v in items.items()]
  File "/home/molguin/dotfiles/dotdrop/dotdrop/dictparser.py", line 39, in <listcomp>
    return [cls.parse(k, v) for k, v in items.items()]
  File "/home/molguin/dotfiles/dotdrop/dotdrop/dictparser.py", line 32, in parse
    return cls(key=key, **newv)
TypeError: __init__() got an unexpected keyword argument 'impignore'
```

**Expected behavior**

Dotdrop should update the imported folder, ignoring whatever was included in `impignore`, as [per the documentation](https://dotdrop.readthedocs.io/en/latest/config/#ignore-patterns).

**Additional information**

The relevant part of the config file
```yaml
d_vim:
  src: vim
  dst: ~/.vim
  impignore:
    - "bundle/*"
```

Dotdrop's execution with the debug logs (`--verbose`)

```console
[DEBUG][dotdrop.options.__init__] #################################################
[DEBUG][dotdrop.options.__init__] #################### DOTDROP ####################
[DEBUG][dotdrop.options.__init__] #################################################
[DEBUG][dotdrop.options.__init__] version: 1.5.4
[DEBUG][dotdrop.options.__init__] command: /home/molguin/dotfiles/dotdrop/dotdrop/dotdrop.py update --verbose
[DEBUG][dotdrop.options.__init__] config file: config.yaml
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] ----------start:/home/molguin/dotfiles/config.yaml----------
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] 
actions:
  post:
    vundle_clone: >
      bash -c 
      "[[ -d ~/.vim/bundle/Vundle.vim ]] || git clone git@github.com:VundleVim/Vundle.vim.git
      ~/.vim/bundle/Vundle.vim"
    vundle_install: vim +PluginClean! +PluginInstall +PluginInstall! +qall
    ycm_compile: >
      bash -c
      "[[ -f ~/.vim/bundle/YouCompleteMe/third_party/ycmd/ycm_core.so ]]|| python3
      ~/.vim/bundle/YouCompleteMe/install.py --all"
config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
  f_starship.toml:
    src: config/starship.toml
    dst: ~/.config/starship.toml
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  d_vim:
    src: vim
    dst: ~/.vim
    impignore:
      - "bundle/*"
  # d_vim_colors:
  #   src: vim/colors
  #   dst: ~/.vim/colors
  # f_vim_filetype.vim:
  #   src: vim/filetype.vim
  #   dst: ~/.vim/filetype.vim
  # d_vim_syntax:
  #   src: vim/syntax
  #   dst: ~/.vim/syntax
  f_python_ycm_venv.py:
    src: .python_ycm_venv.py
    dst: ~/.python_ycm_venv.py
  f_xinitrc:
    src: xinitrc
    dst: ~/.xinitrc
  f_zprofile:
    src: zprofile
    dst: ~/.zprofile
  f_profile:
    src: profile
    dst: ~/.profile
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
profiles:
  base:
    dotfiles:
      - f_xinitrc
      - f_zprofile
      - f_profile
      - f_zshrc
      - f_starship.toml
  vim:
    dotfiles:
      - f_vimrc
      - d_vim
      # - f_vim_filetype.vim
      # - d_vim_syntax
      # - d_vim_colors
      - f_python_ycm_venv.py
    actions:
      - vundle_clone
      - vundle_install
      - ycm_compile
  molguinGE66Arch:
    include:
      - base
      - vim
    dotfiles:
      - d_kitty
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] ----------end:/home/molguin/dotfiles/config.yaml----------
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] normalizing relative to cfg: dotfiles -> /home/molguin/dotfiles/dotfiles
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] settings block::
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "backup": True
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "banner": True
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "create": True
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "dotpath": /home/molguin/dotfiles/dotfiles
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "ignoreempty": False
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "keepdot": False
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "link_dotfile_default": nolink
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "link_on_import": nolink
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "longkey": False
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "showdiff": False
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "workdir": /home/molguin/.config/dotdrop
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "minversion": None
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "diff_command": diff -r -u {0} {1}
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "template_dotfile_default": True
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "ignore_missing_in_dotdrop": False
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "force_chmod": False
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "default_actions": []
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "import_actions": []
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "import_configs": []
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "import_variables": []
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "cmpignore": []
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "upignore": []
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "instignore": []
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "impignore": []
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "func_file": []
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "filter_file": []
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] variables block:
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] dynvariables block:
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] current variables defined:
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "profile": molguinGE66Arch
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "_dotdrop_dotpath": /home/molguin/dotfiles/dotfiles
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "_dotdrop_cfgpath": /home/molguin/dotfiles/config.yaml
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "_dotdrop_workdir": /home/molguin/.config/dotdrop
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] profiles block:
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "base": ordereddict([('dotfiles', ['f_xinitrc', 'f_zprofile', 'f_profile', 'f_zshrc', 'f_starship.toml'])])
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "vim": ordereddict([('dotfiles', ['f_vimrc', 'd_vim', 'f_python_ycm_venv.py']), ('actions', ['vundle_clone', 'vundle_install', 'ycm_compile'])])
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "molguinGE66Arch": ordereddict([('include', ['base', 'vim']), ('dotfiles', ['d_kitty'])])
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] included variables from base: {}
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] included variables from vim: {}
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] included dynvariables from base: {}
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] included dynvariables from vim: {}
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] current variables defined:
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "profile": molguinGE66Arch
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "_dotdrop_dotpath": /home/molguin/dotfiles/dotfiles
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "_dotdrop_cfgpath": /home/molguin/dotfiles/config.yaml
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "_dotdrop_workdir": /home/molguin/.config/dotdrop
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] current variables defined:
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "profile": molguinGE66Arch
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "_dotdrop_dotpath": /home/molguin/dotfiles/dotfiles
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "_dotdrop_cfgpath": /home/molguin/dotfiles/config.yaml
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "_dotdrop_workdir": /home/molguin/.config/dotdrop
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] dotfiles block:
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "d_kitty": ordereddict([('src', 'config/kitty'), ('dst', '~/.config/kitty'), ('link', 'nolink'), ('ignoreempty', False), ('template', True)])
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "f_starship.toml": ordereddict([('src', 'config/starship.toml'), ('dst', '~/.config/starship.toml'), ('link', 'nolink'), ('ignoreempty', False), ('template', True)])
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "f_vimrc": ordereddict([('src', 'vimrc'), ('dst', '~/.vimrc'), ('link', 'nolink'), ('ignoreempty', False), ('template', True)])
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "d_vim": ordereddict([('src', 'vim'), ('dst', '~/.vim'), ('impignore', ['bundle/*']), ('link', 'nolink'), ('ignoreempty', False), ('template', True)])
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "f_python_ycm_venv.py": ordereddict([('src', '.python_ycm_venv.py'), ('dst', '~/.python_ycm_venv.py'), ('link', 'nolink'), ('ignoreempty', False), ('template', True)])
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "f_xinitrc": ordereddict([('src', 'xinitrc'), ('dst', '~/.xinitrc'), ('link', 'nolink'), ('ignoreempty', False), ('template', True)])
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "f_zprofile": ordereddict([('src', 'zprofile'), ('dst', '~/.zprofile'), ('link', 'nolink'), ('ignoreempty', False), ('template', True)])
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "f_profile": ordereddict([('src', 'profile'), ('dst', '~/.profile'), ('link', 'nolink'), ('ignoreempty', False), ('template', True)])
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "f_zshrc": ordereddict([('src', 'zshrc'), ('dst', '~/.zshrc'), ('link', 'nolink'), ('ignoreempty', False), ('template', True)])
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] actions block:
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "vundle_clone": ('post', 'bash -c  "[[ -d ~/.vim/bundle/Vundle.vim ]] || git clone git@github.com:VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim"\n')
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "vundle_install": ('post', 'vim +PluginClean! +PluginInstall +PluginInstall! +qall')
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "ycm_compile": ('post', 'bash -c "[[ -f ~/.vim/bundle/YouCompleteMe/third_party/ycmd/ycm_core.so ]]|| python3 ~/.vim/bundle/YouCompleteMe/install.py --all"\n')
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] trans_r block:
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] trans_w block:
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] molguinGE66Arch includes base,vim
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] molguinGE66Arch dotfiles before include: ['d_kitty']
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] molguinGE66Arch actions before include: []
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] resolving includes "molguinGE66Arch" <- "base"
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] recursively resolving includes for profile "base"
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] Merging dotfiles molguinGE66Arch <- base: ['d_kitty'] <- ['f_xinitrc', 'f_zprofile', 'f_profile', 'f_zshrc', 'f_starship.toml']
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] Merging actions molguinGE66Arch <- base: [] <- []
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] resolving includes "molguinGE66Arch" <- "vim"
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] recursively resolving includes for profile "vim"
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] Merging dotfiles molguinGE66Arch <- vim: ['d_kitty', 'f_xinitrc', 'f_zprofile', 'f_profile', 'f_zshrc', 'f_starship.toml'] <- ['f_vimrc', 'd_vim', 'f_python_ycm_venv.py']
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] Merging actions molguinGE66Arch <- vim: [] <- ['vundle_clone', 'vundle_install', 'ycm_compile']
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] molguinGE66Arch dotfiles after include: ['d_kitty', 'f_xinitrc', 'f_zprofile', 'f_profile', 'f_zshrc', 'f_starship.toml', 'f_vimrc', 'd_vim', 'f_python_ycm_venv.py']
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] molguinGE66Arch actions after include: ['vundle_clone', 'vundle_install', 'ycm_compile']
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] templating dotfiles entries
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] ########### final config ###########
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] Current entries
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] entry settings:
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "backup": True
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "banner": True
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "create": True
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "dotpath": /home/molguin/dotfiles/dotfiles
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "ignoreempty": False
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "keepdot": False
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "link_dotfile_default": nolink
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "link_on_import": nolink
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "longkey": False
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "showdiff": False
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "workdir": /home/molguin/.config/dotdrop
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "minversion": None
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "diff_command": diff -r -u {0} {1}
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "template_dotfile_default": True
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "ignore_missing_in_dotdrop": False
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "force_chmod": False
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "default_actions": []
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "import_actions": []
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "import_configs": []
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "import_variables": []
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "cmpignore": []
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "upignore": []
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "instignore": []
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "impignore": []
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "func_file": []
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "filter_file": []
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] entry dotfiles:
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "d_kitty": ordereddict([('src', '/home/molguin/dotfiles/dotfiles/config/kitty'), ('dst', '/home/molguin/.config/kitty'), ('link', 'nolink'), ('ignoreempty', False), ('template', True)])
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "f_starship.toml": ordereddict([('src', '/home/molguin/dotfiles/dotfiles/config/starship.toml'), ('dst', '/home/molguin/.config/starship.toml'), ('link', 'nolink'), ('ignoreempty', False), ('template', True)])
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "f_vimrc": ordereddict([('src', '/home/molguin/dotfiles/dotfiles/vimrc'), ('dst', '/home/molguin/.vimrc'), ('link', 'nolink'), ('ignoreempty', False), ('template', True)])
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "d_vim": ordereddict([('src', '/home/molguin/dotfiles/dotfiles/vim'), ('dst', '/home/molguin/.vim'), ('impignore', ['bundle/*']), ('link', 'nolink'), ('ignoreempty', False), ('template', True)])
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "f_python_ycm_venv.py": ordereddict([('src', '/home/molguin/dotfiles/dotfiles/.python_ycm_venv.py'), ('dst', '/home/molguin/.python_ycm_venv.py'), ('link', 'nolink'), ('ignoreempty', False), ('template', True)])
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "f_xinitrc": ordereddict([('src', '/home/molguin/dotfiles/dotfiles/xinitrc'), ('dst', '/home/molguin/.xinitrc'), ('link', 'nolink'), ('ignoreempty', False), ('template', True)])
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "f_zprofile": ordereddict([('src', '/home/molguin/dotfiles/dotfiles/zprofile'), ('dst', '/home/molguin/.zprofile'), ('link', 'nolink'), ('ignoreempty', False), ('template', True)])
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "f_profile": ordereddict([('src', '/home/molguin/dotfiles/dotfiles/profile'), ('dst', '/home/molguin/.profile'), ('link', 'nolink'), ('ignoreempty', False), ('template', True)])
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "f_zshrc": ordereddict([('src', '/home/molguin/dotfiles/dotfiles/zshrc'), ('dst', '/home/molguin/.zshrc'), ('link', 'nolink'), ('ignoreempty', False), ('template', True)])
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] entry profiles:
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "base": ordereddict([('dotfiles', ['f_xinitrc', 'f_zprofile', 'f_profile', 'f_zshrc', 'f_starship.toml'])])
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "vim": ordereddict([('dotfiles', ['f_vimrc', 'd_vim', 'f_python_ycm_venv.py']), ('actions', ['vundle_clone', 'vundle_install', 'ycm_compile'])])
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "molguinGE66Arch": ordereddict([('include', []), ('dotfiles', ['d_kitty', 'f_xinitrc', 'f_zprofile', 'f_profile', 'f_zshrc', 'f_starship.toml', 'f_vimrc', 'd_vim', 'f_python_ycm_venv.py']), ('actions', ['vundle_clone', 'vundle_install', 'ycm_compile'])])
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] entry actions:
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "vundle_clone": ('post', 'bash -c  "[[ -d ~/.vim/bundle/Vundle.vim ]] || git clone git@github.com:VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim"\n')
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "vundle_install": ('post', 'vim +PluginClean! +PluginInstall +PluginInstall! +qall')
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "ycm_compile": ('post', 'bash -c "[[ -f ~/.vim/bundle/YouCompleteMe/third_party/ycmd/ycm_core.so ]]|| python3 ~/.vim/bundle/YouCompleteMe/install.py --all"\n')
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] entry trans_r:
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] entry trans_w:
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] entry variables:
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "profile": molguinGE66Arch
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "_dotdrop_dotpath": /home/molguin/dotfiles/dotfiles
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "_dotdrop_cfgpath": /home/molguin/dotfiles/config.yaml
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]    - "_dotdrop_workdir": /home/molguin/.config/dotdrop
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/molguin/dotfiles/dotdrop/dotdrop/dotdrop.py", line 848, in <module>
    if main():
  File "/home/molguin/dotfiles/dotdrop/dotdrop/dotdrop.py", line 819, in main
    opts = Options()
  File "/home/molguin/dotfiles/dotdrop/dotdrop/options.py", line 157, in __init__
    self._read_config()
  File "/home/molguin/dotfiles/dotdrop/dotdrop/options.py", line 219, in _read_config
    self.conf = Cfg(self.confpath, self.profile, debug=self.debug,
  File "/home/molguin/dotfiles/dotdrop/dotdrop/cfg_aggregator.py", line 45, in __init__
    self._load()
  File "/home/molguin/dotfiles/dotdrop/dotdrop/cfg_aggregator.py", line 219, in _load
    self.dotfiles = Dotfile.parse_dict(self.cfgyaml.dotfiles)
  File "/home/molguin/dotfiles/dotdrop/dotdrop/dictparser.py", line 39, in parse_dict
    return [cls.parse(k, v) for k, v in items.items()]
  File "/home/molguin/dotfiles/dotdrop/dotdrop/dictparser.py", line 39, in <listcomp>
    return [cls.parse(k, v) for k, v in items.items()]
  File "/home/molguin/dotfiles/dotdrop/dotdrop/dictparser.py", line 32, in parse
    return cls(key=key, **newv)
TypeError: __init__() got an unexpected keyword argument 'impignore'
```

**Comment by deadc0de6** [comment]
Thanks for submitting your issue. Actually it is not a bug but an issue with the documentation. 
What you're trying to use is `upignore` (since you want to ignore patterns when updating a dotfile) and not `impignore` (which is related to a global config to ignore specific files when importing).

The [doc here](https://dotdrop.readthedocs.io/en/latest/config-format/) is correct and doesn't list `impignore` in the dotfile block but the [doc here](https://dotdrop.readthedocs.io/en/latest/config/#ignore-patterns) wrongly shows an example with `impignore` inside a dotfile block (should be `upignore`).

I'll fix the documentation, thanks for pointing that out!

**Comment by molguin92** [comment]
Thank you! I haven't had time to test this out yet but I will. Thank you for a great piece of software.
