### ISSUE TITLE
Error while updating directory

### ISSUE THREAD

**Issue by fwarmuth** [deadc0de6/dotdrop#36]
Hey there,
i just started using dotdrop, love it so far.

but if i want to update whole dir i get an error.

**situation:**

`>> dotdrop import ~/.config/rofi/rofi-scripts-collection`

results in the following config.yam:
```
... 
d_rofi-scripts-collection:
    dst: ~/.config/rofi/rofi-scripts-collection
    src: config/rofi/rofi-scripts-collection
...
```
Try to update the whole dir results in:
```
>> dotdrop update ~/.config/rofi/rofi-scripts-collection 
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/XXXXX/dotfiles/dotdrop/dotdrop/dotdrop.py", line 355, in <module>
    if main():
  File "/home/XXXXX/dotfiles/dotdrop/dotdrop/dotdrop.py", line 345, in main
    update(opts, conf, args['<path>'])
  File "/home/felix/Data/dotfiles/dotdrop/dotdrop/dotdrop.py", line 200, in update
    if Templategen.get_marker() in open(src, 'r').read():
IsADirectoryError: [Errno 21] Is a directory: '/home/XXXXX/dotfiles/dotfiles/config/rofi/rofi-scripts-collection'
```

Seems that dotdrop thinks its a single file, but the import is correct?

regards!

**Comment by ziirish** [comment]
Hi,

Can you have a try at this patch?

```diff
diff --git a/dotdrop/dotdrop.py b/dotdrop/dotdrop.py
index e708953..cfe1867 100644
--- a/dotdrop/dotdrop.py
+++ b/dotdrop/dotdrop.py
@@ -209,7 +209,8 @@ def update(opts, conf, path):
         return False
     dotfile = subs[0]
     src = os.path.join(conf.get_abs_dotpath(opts['dotpath']), dotfile.src)
-    if Templategen.get_marker() in open(src, 'r').read():
+    if os.path.isfile(src) and \
+            Templategen.get_marker() in open(src, 'r').read():
         LOG.warn('\"{}\" uses template, please update manually'.format(src))
         return False
     cmd = ['cp', '-R', '-L', os.path.expanduser(path), src]
```

**Comment by deadc0de6** [comment]
It was indeed a bug.
Thanks to @ziirish for fixing it.

I have merged the PR which fixes this. Let me know if you still have issues with it.
