### ISSUE TITLE
Templating a file inside a symlinked parent folder

### ISSUE THREAD

**Issue by belugame** [deadc0de6/dotdrop#58]
I have a folder with files all related to configuring my mutt with multiple accounts. The general rc, contacts, signatures, theme, and several account files that also hold the passwords etc.

Now, initially I used dotdrop to link the whole folder and then tried to use env vars to replace the credentials in the nested account files.. but that does not work as it is already symlinked by the parent folder...

This won't work:

    ~/.mutt:
        src: mutt
        dst: ~/.mutt
        link: true
    ~/.mutt/accounts/myaccount.offlineimap:
        src: mutt/accounts/myaccount.offlineimap
        dst: ~/.mutt/accounts/myaccount.offlineimap
        link: true

Now I could link all file by file, but is there a smarter way to link the whole bunch but template a few?

**Comment by belugame** [comment]
Thank you very much for the rapid implementation and your work in general!
I have checked out master (0d4ce18e4965f7) but `dotbot.sh` does not like my config.yaml anymore.
```
 [~/code/dotdrop]$ ./dotdrop.sh install -c ~/dot/config.yaml
     _       _      _                                                 
  __| | ___ | |_ __| |_ __ ___  _ __
 / _` |/ _ \| __/ _` | '__/ _ \| '_ |
 \__,_|\___/ \__\__,_|_|  \___/| .__/  v0.20.3
                               |_|

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/martin/code/dotdrop/dotdrop/dotdrop.py", line 398, in <module>
    if main():
  File "/home/martin/code/dotdrop/dotdrop/dotdrop.py", line 369, in main
    ret = install(opts, conf, temporary=args['--temp'])
  File "/home/martin/code/dotdrop/dotdrop/dotdrop.py", line 107, in install
    r = inst.link(t, dotfile.src, dotfile.dst)
  File "/home/martin/code/dotdrop/dotdrop/installer.py", line 59, in link
    if Templategen.is_template(src):
  File "/home/martin/code/dotdrop/dotdrop/templategen.py", line 99, in is_template
    for entry in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/foo/dot/./zlogin'
```
Is `dotpath: .` wrong? when my `config.yaml` and the dotfiles are in the same folder?
I could confirm when I reset the repo to the commit of your last release it has no error.

Here's my `config.yaml`: https://pastebin.com/7f2eJDz5

**Comment by deadc0de6** [comment]
No `dotpath: .` is fine and should work. 

Is `/home/foo/dot/./zlogin` meant to be a directory? May I ask what does `file /home/foo/dot/./zlogin` return?

**Comment by deadc0de6** [comment]
Hm my guess is that `/home/foo/dot/./zlogin` does not exist anymore ... I will add an additional check to warn about non-existing dotfile in the dotpath.

**Comment by belugame** [comment]
Ooh my mistake. You are right, the latest master did point out wrong paths in my config that the current release did simply ignore. So good on ya! I m still trying out, will report back.

**Comment by belugame** [comment]
On a side note, here: https://github.com/deadc0de6/dotdrop/blob/master/dotdrop/templategen.py#L117
it fails with a UnicodeDecodeError on a binary file that I have in my dotfiles. It is this little util in its compiled form  https://github.com/nonpop/xkblayout-state

**Comment by deadc0de6** [comment]
FYI I added a few more tests to ensure the dotfile exists in the dotpath (d36e525ca4767d97ef75ecf3c620a96cdd3606b5).

**Comment by belugame** [comment]
yes! the templating works lovely now

`MY_VAR=ohhello ~/code/dotdrop/dotdrop.sh  install -c /home/foo/dot/config.yaml`

**Comment by deadc0de6** [comment]
last commit should fix your issue with binaries.

**Comment by belugame** [comment]
Wow, you are the best!

I found 2 more minor things now. When you install a dotfile with a variable 
1)
```
foo
{{@@ env['MY_VAR'] @@}}` 
bar
```
then change the template to

```
foo

bar
```
and redeploy, the 2nd line in the deployed dotfile will still hold the old variable name of the first deploy, rather than be empty.

2) It asks me `Remove "/home/foo/.mutt" for link creation? [y/N]` for deploying even though I only touched the nested file. For me that is unexpected.

**Comment by deadc0de6** [comment]
It asks because you moved from a template dotfile to a non-template dotfile. The templated dotfiles are first installed to `workdir` (per default `~/.config/dotdrop`) and then symlinked. The non-templated dotfiles are directly symlinked to the `dotpath`.

```
# with template
/home/user/.xyz -> /home/user/.config/dotdrop/.xyz
# without template
/home/user/.xyz -> /home/user/dots/dotfiles/xyz
```

I guess your issue came from the fact that the symlink wasn't re-created when moving from one to the other. It is hopefully fixed with d86567a861ba4c53d245cc022680a9f60f1ab18a.

**Comment by deadc0de6** [comment]
Thanks again for your help on testing this, much appreciated :+1:
