### ISSUE TITLE
Should I always use absolute path when import dotfiles?

### ISSUE THREAD

**Issue by roachsinai** [deadc0de6/dotdrop#60]
Today when I install dotfiles I get error:

```
➜  dotfiles git:(master) ✗ /usr/bin/dotdrop --cfg=~/dotfiles/config.yaml install  
     _       _      _
  __| | ___ | |_ __| |_ __ ___  _ __
 / _` |/ _ \| __/ _` | '__/ _ \| '_ |
 \__,_|\___/ \__\__,_|_|  \___/| .__/  v0.20.1
                               |_|

Traceback (most recent call last):
  File "/usr/bin/dotdrop", line 11, in <module>
    load_entry_point('dotdrop==0.20.1', 'console_scripts', 'dotdrop')()
  File "/usr/lib/python3.7/site-packages/dotdrop/__init__.py", line 11, in main
    if dotdrop.dotdrop.main():
  File "/usr/lib/python3.7/site-packages/dotdrop/dotdrop.py", line 369, in main
    ret = install(opts, conf, temporary=args['--temp'])
  File "/usr/lib/python3.7/site-packages/dotdrop/dotdrop.py", line 116, in install
    r = inst.install(t, src, dotfile.dst)
  File "/usr/lib/python3.7/site-packages/dotdrop/installer.py", line 50, in install
    return self._handle_file(templater, src, dst)
  File "/usr/lib/python3.7/site-packages/dotdrop/installer.py", line 116, in _handle_file
    ret = self._write(dst, content, st.st_mode)
  File "/usr/lib/python3.7/site-packages/dotdrop/installer.py", line 172, in _write
    if not self._create_dirs(base):
  File "/usr/lib/python3.7/site-packages/dotdrop/installer.py", line 197, in _create_dirs
    os.makedirs(directory)
  File "/usr/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''
```

But, if I use `/usr/bin/dotdrop --cfg=~/dotfiles/config.yaml install -t` they are good, no errors.

Finally, I trace it use `ipdb` and find I import a file name like `.to_import.sh` directory,

```
➜  ~ ls | grep import
.to_import.sh
➜ dotdrop import .to_import.sh
...
```

and then when I install dotfiles I get above error when I'm not in dir `~`.

---

There are two palces found `absolute` in `README.md`. But, it doesn't specific that I have to use absolute path when import dotfiles(I thought this great tool ,dotdrop, should do it before, lol). Your `import examples is good`.

So I think it's good to specific it at README.md.

**Comment by roachsinai** [comment]
Yes, installed by pypi,  and it's my honour to test new features.

And I think new feature, ` if a relative path is passed to the import command it will be updated to an absolute path`, also directly documented with new version will be fine too.

**Comment by roachsinai** [comment]
Today I'm setup my WSL on Win10, so I check it at wsl.

Dotdrop works well now at user home dir about relative path file, for me `/home/roach`.

```
➜  ~ sudo pip3 install dotdrop -U
The directory '/home/roach/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/roach/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting dotdrop
  Downloading https://files.pythonhosted.org/packages/e9/49/b04f3e42be1f1d284a4901f0c12126e7769d6d8dc14d773a750e3ee8bd5b/dotdrop-0.21.1-py3-none-any.whl (41kB)
    100% |████████████████████████████████| 51kB 39kB/s
Requirement already up-to-date: Jinja2 in /usr/lib/python3/dist-packages (from dotdrop)
Collecting PyYAML (from dotdrop)
  Downloading https://files.pythonhosted.org/packages/9e/a3/1d13970c3f36777c583f136c136f804d70f500168edc1edea6daa7200769/PyYAML-3.13.tar.gz (270kB)
    100% |████████████████████████████████| 276kB 29kB/s
Requirement already up-to-date: docopt in /usr/local/lib/python3.6/dist-packages (from dotdrop)
Installing collected packages: PyYAML, dotdrop
  Found existing installation: PyYAML 3.12
    Not uninstalling pyyaml at /usr/lib/python3/dist-packages, outside environment /usr
  Running setup.py install for PyYAML ... done
  Found existing installation: dotdrop 0.21.0
    Uninstalling dotdrop-0.21.0:
      Successfully uninstalled dotdrop-0.21.0
Successfully installed PyYAML-3.13 dotdrop-0.21.1
➜  ~ vim .dotdrop.test
➜  ~ cat .dotdrop.test
# file for dotdrop test.
➜  ~ dotdrop import .dotdrop.test
     _       _      _
  __| | ___ | |_ __| |_ __ ___  _ __
 / _` |/ _ \| __/ _` | '__/ _ \| '_ |
 \__,_|\___/ \__\__,_|_|  \___/| .__/  v0.21.1
                               |_|

        -> ".dotdrop.test" imported

1 file(s) imported.
➜  ~ git:() cat dotfiles/config.yaml
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_by_default: false
  longkey: false
  workdir: ~/.config/dotdrop
dotfiles:
  f_dircolors:
    dst: ~/.dircolors
    src: dircolors
  f_dotdrop.test:
    dst: ~/.dotdrop.test
    src: dotdrop.test
  f_git-diff-wrapper.sh:
    dst: ~/.git-diff-wrapper.sh
    src: git-diff-wrapper.sh
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  f_profile:
    dst: ~/.profile
    src: profile
  f_proxychains.conf:
    dst: ~/.proxychains/proxychains.conf
    src: proxychains/proxychains.conf
  f_vimrc:
    dst: ~/.vimrc
    src: vimrc
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
profiles:
  hman:
    dotfiles:
    - f_vimrc
    - f_gitconfig
    - f_zshrc
    - f_dircolors
    - f_git-diff-wrapper.sh
    - f_profile
    - f_proxychains.conf
  hwin:
    dotfiles:
    - f_vimrc
    - f_gitconfig
    - f_zshrc
    - f_dircolors
    - f_git-diff-wrapper.sh
    - f_dotdrop.test
➜  ~ dotdrop install
     _       _      _
  __| | ___ | |_ __| |_ __ ___  _ __
 / _` |/ _ \| __/ _` | '__/ _ \| '_ |
 \__,_|\___/ \__\__,_|_|  \___/| .__/  v0.21.1
                               |_|


0 dotfile(s) installed.
➜  ~
```

Forget about `git()`, it appear sometimes I exec a command.

But seems a problem at a mount partition like `D:/` for Win10 is mounted at `/mnt/d`.

```
➜  d dotdrop import library_wifi.txt
     _       _      _
  __| | ___ | |_ __| |_ __ ___  _ __
 / _` |/ _ \| __/ _` | '__/ _ \| '_ |
 \__,_|\___/ \__\__,_|_|  \___/| .__/  v0.21.1
                               |_|

        -> "library_wifi.txt" imported

1 file(s) imported.
➜  d dotdrop install
     _       _      _
  __| | ___ | |_ __| |_ __ ___  _ __
 / _` |/ _ \| __/ _` | '__/ _ \| '_ |
 \__,_|\___/ \__\__,_|_|  \___/| .__/  v0.21.1
                               |_|

[ERR] source dotfile does not exist: /home/roach/dotfiles/dotfiles/mnt/d/library_wifi.txt
[ERR] source dotfile does not exist: "/home/roach/dotfiles/dotfiles/mnt/d/library_wifi.txt"

0 dotfile(s) installed.
➜  d pwd
/mnt/d
```

And maybe it's not a problem, a dotfile maybe never set at a mount parition, I mean very few.

**Comment by deadc0de6** [comment]
Thanks for reporting this.

It is ok to have a dotfile from a mount partition, it shouldn't be an issue. I'm however unable to reproduce your problem. 

Can you provide me with more information:
* the entry in the `config.yaml` for the `library_wifi.txt` dotfile (after it is imported)
* run the `import` command with `-V` (for verbose)
* run the `install` command with `-V` (for verbose)
* a listing of files in your dotpath after the `import` (`ls -R` or `tree`)

It looks as if the dotfile is not copied to the `dotpath` ...

**Comment by roachsinai** [comment]
Yse, I cannot find the `library_wifi.txt` file at `dotpath` yesterday.

```
➜  d dotdrop import library_wifi.txt
     _       _      _
  __| | ___ | |_ __| |_ __ ___  _ __
 / _` |/ _ \| __/ _` | '__/ _ \| '_ |
 \__,_|\___/ \__\__,_|_|  \___/| .__/  v0.21.1
                               |_|

        -> "library_wifi.txt" imported

1 file(s) imported.
➜  d dotdrop install
     _       _      _
  __| | ___ | |_ __| |_ __ ___  _ __
 / _` |/ _ \| __/ _` | '__/ _ \| '_ |
 \__,_|\___/ \__\__,_|_|  \___/| .__/  v0.21.1
                               |_|

[ERR] source dotfile does not exist: /home/roach/dotfiles/dotfiles/mnt/d/library_wifi.txt
[ERR] source dotfile does not exist: "/home/roach/dotfiles/dotfiles/mnt/d/library_wifi.txt"

0 dotfile(s) installed.
➜  d cat ~/dotfiles/config.yaml
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_by_default: false
  longkey: false
  workdir: ~/.config/dotdrop
dotfiles:
  f_dircolors:
    dst: ~/.dircolors
    src: dircolors
  f_git-diff-wrapper.sh:
    dst: ~/.git-diff-wrapper.sh
    src: git-diff-wrapper.sh
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  f_library_wifi.txt:
    dst: /mnt/d/library_wifi.txt
    src: mnt/d/library_wifi.txt
  f_profile:
    dst: ~/.profile
    src: profile
  f_proxychains.conf:
    dst: ~/.proxychains/proxychains.conf
    src: proxychains/proxychains.conf
  f_vimrc:
    dst: ~/.vimrc
    src: vimrc
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
profiles:
  hman:
    dotfiles:
    - f_vimrc
    - f_gitconfig
    - f_zshrc
    - f_dircolors
    - f_git-diff-wrapper.sh
    - f_profile
    - f_proxychains.conf
  hwin:
    dotfiles:
    - f_vimrc
    - f_gitconfig
    - f_zshrc
    - f_dircolors
    - f_git-diff-wrapper.sh
    - f_library_wifi.txt
➜  d dotdrop import library_wifi.txt -V
[DEBUG][dotdrop.dotdrop.main] config file: ~/dotfiles/config.yaml
[DEBUG][dotdrop.dotdrop.main] opts: {'backup': True, 'banner': True, 'create': True, 'dotpath': '/home/roach/dotfiles/dotfiles', 'keepdot': False, 'link_by_default': False, 'longkey': False, 'workdir': '~/.config/dotdrop', 'dry': False, 'profile': 'hwin', 'safe': True, 'installdiff': True, 'link': False, 'debug': True, 'variables': {}}
     _       _      _
  __| | ___ | |_ __| |_ __ ___  _ __
 / _` |/ _ \| __/ _` | '__/ _ \| '_ |
 \__,_|\___/ \__\__,_|_|  \___/| .__/  v0.21.1
                               |_|

[ERR] "f_library_wifi.txt" already present
[DEBUG][dotdrop.utils.run] exec: mkdir -p /home/roach/dotfiles/dotfiles/mnt/d
[DEBUG][dotdrop.utils.run] exec: cp -R -L /mnt/d/library_wifi.txt /home/roach/dotfiles/dotfiles/mnt/d/library_wifi.txt
[WARN] "library_wifi.txt" ignored

0 file(s) imported.
➜  d dotdrop install -V
[DEBUG][dotdrop.dotdrop.main] config file: ~/dotfiles/config.yaml
[DEBUG][dotdrop.dotdrop.main] opts: {'backup': True, 'banner': True, 'create': True, 'dotpath': '/home/roach/dotfiles/dotfiles', 'keepdot': False, 'link_by_default': False, 'longkey': False, 'workdir': '~/.config/dotdrop', 'dry': False, 'profile': 'hwin', 'safe': True, 'installdiff': True, 'link': False, 'debug': True, 'variables': {}}
     _       _      _
  __| | ___ | |_ __| |_ __ ___  _ __
 / _` |/ _ \| __/ _` | '__/ _ \| '_ |
 \__,_|\___/ \__\__,_|_|  \___/| .__/  v0.21.1
                               |_|

[DEBUG][dotdrop.dotdrop.install] installing key:"f_dircolors", src:"dircolors", dst:"~/.dircolors", link:"False"
[DEBUG][dotdrop.installer.install] install /home/roach/dotfiles/dotfiles/dircolors to /home/roach/.dircolors
[DEBUG][dotdrop.installer._handle_file] generate template for /home/roach/dotfiles/dotfiles/dircolors
[DEBUG][dotdrop.utils.run] exec: file -b /home/roach/dotfiles/dotfiles/dircolors
[DEBUG][dotdrop.templategen._handle_file] "/home/roach/dotfiles/dotfiles/dircolors" filetype: ASCII text
[DEBUG][dotdrop.templategen._handle_file] "/home/roach/dotfiles/dotfiles/dircolors" is text: True
[DEBUG][dotdrop.installer._write] /home/roach/.dircolors is the same
[DEBUG][dotdrop.installer._handle_file] ignoring "/home/roach/.dircolors", same content
[DEBUG][dotdrop.dotdrop.install] installing key:"f_git-diff-wrapper.sh", src:"git-diff-wrapper.sh", dst:"~/.git-diff-wrapper.sh", link:"False"
[DEBUG][dotdrop.installer.install] install /home/roach/dotfiles/dotfiles/git-diff-wrapper.sh to /home/roach/.git-diff-wrapper.sh
[DEBUG][dotdrop.installer._handle_file] generate template for /home/roach/dotfiles/dotfiles/git-diff-wrapper.sh
[DEBUG][dotdrop.utils.run] exec: file -b /home/roach/dotfiles/dotfiles/git-diff-wrapper.sh
[DEBUG][dotdrop.templategen._handle_file] "/home/roach/dotfiles/dotfiles/git-diff-wrapper.sh" filetype: Bourne-Again shell script, ASCII text executable
[DEBUG][dotdrop.templategen._handle_file] "/home/roach/dotfiles/dotfiles/git-diff-wrapper.sh" is text: True
[DEBUG][dotdrop.installer._write] /home/roach/.git-diff-wrapper.sh is the same
[DEBUG][dotdrop.installer._handle_file] ignoring "/home/roach/.git-diff-wrapper.sh", same content
[DEBUG][dotdrop.dotdrop.install] installing key:"f_gitconfig", src:"gitconfig", dst:"~/.gitconfig", link:"False"
[DEBUG][dotdrop.installer.install] install /home/roach/dotfiles/dotfiles/gitconfig to /home/roach/.gitconfig
[DEBUG][dotdrop.installer._handle_file] generate template for /home/roach/dotfiles/dotfiles/gitconfig
[DEBUG][dotdrop.utils.run] exec: file -b /home/roach/dotfiles/dotfiles/gitconfig
[DEBUG][dotdrop.templategen._handle_file] "/home/roach/dotfiles/dotfiles/gitconfig" filetype: UTF-8 Unicode text
[DEBUG][dotdrop.templategen._handle_file] "/home/roach/dotfiles/dotfiles/gitconfig" is text: True
[DEBUG][dotdrop.installer._write] /home/roach/.gitconfig is the same
[DEBUG][dotdrop.installer._handle_file] ignoring "/home/roach/.gitconfig", same content
[DEBUG][dotdrop.dotdrop.install] installing key:"f_library_wifi.txt", src:"mnt/d/library_wifi.txt", dst:"/mnt/d/library_wifi.txt", link:"False"
[ERR] source dotfile does not exist: /home/roach/dotfiles/dotfiles/mnt/d/library_wifi.txt
[DEBUG][dotdrop.installer.install] install /home/roach/dotfiles/dotfiles/mnt/d/library_wifi.txt to /mnt/d/library_wifi.txt
[DEBUG][dotdrop.installer._handle_file] generate template for /home/roach/dotfiles/dotfiles/mnt/d/library_wifi.txt
[ERR] source dotfile does not exist: "/home/roach/dotfiles/dotfiles/mnt/d/library_wifi.txt"
[DEBUG][dotdrop.dotdrop.install] installing key:"f_vimrc", src:"vimrc", dst:"~/.vimrc", link:"False"
[DEBUG][dotdrop.installer.install] install /home/roach/dotfiles/dotfiles/vimrc to /home/roach/.vimrc
[DEBUG][dotdrop.installer._handle_file] generate template for /home/roach/dotfiles/dotfiles/vimrc
[DEBUG][dotdrop.utils.run] exec: file -b /home/roach/dotfiles/dotfiles/vimrc
[DEBUG][dotdrop.templategen._handle_file] "/home/roach/dotfiles/dotfiles/vimrc" filetype: UTF-8 Unicode text
[DEBUG][dotdrop.templategen._handle_file] "/home/roach/dotfiles/dotfiles/vimrc" is text: True
[DEBUG][dotdrop.installer._write] /home/roach/.vimrc is the same
[DEBUG][dotdrop.installer._handle_file] ignoring "/home/roach/.vimrc", same content
[DEBUG][dotdrop.dotdrop.install] installing key:"f_zshrc", src:"zshrc", dst:"~/.zshrc", link:"False"
[DEBUG][dotdrop.installer.install] install /home/roach/dotfiles/dotfiles/zshrc to /home/roach/.zshrc
[DEBUG][dotdrop.installer._handle_file] generate template for /home/roach/dotfiles/dotfiles/zshrc
[DEBUG][dotdrop.utils.run] exec: file -b /home/roach/dotfiles/dotfiles/zshrc
[DEBUG][dotdrop.templategen._handle_file] "/home/roach/dotfiles/dotfiles/zshrc" filetype: UTF-8 Unicode text
[DEBUG][dotdrop.templategen._handle_file] "/home/roach/dotfiles/dotfiles/zshrc" is text: True
[DEBUG][dotdrop.installer._write] /home/roach/.zshrc is the same
[DEBUG][dotdrop.installer._handle_file] ignoring "/home/roach/.zshrc", same content

0 dotfile(s) installed.
```

**Comment by roachsinai** [comment]
But, look the install info between `library_wifi.txt` and `.zshrc`, there is alse an error install path `install /home/roach/dotfiles/dotfiles/mnt/d/library_wifi.txt to /mnt/d/library_wifi.txt`.

```
[DEBUG][dotdrop.dotdrop.install] installing key:"f_library_wifi.txt", src:"mnt/d/library_wifi.txt", dst:"/mnt/d/library_wifi.txt", link:"False"
[ERR] source dotfile does not exist: /home/roach/dotfiles/dotfiles/mnt/d/library_wifi.txt
[DEBUG][dotdrop.installer.install] install /home/roach/dotfiles/dotfiles/mnt/d/library_wifi.txt to /mnt/d/library_wifi.txt
[DEBUG][dotdrop.installer._handle_file] generate template for /home/roach/dotfiles/dotfiles/mnt/d/library_wifi.txt
[ERR] source dotfile does not exist: "/home/roach/dotfiles/dotfiles/mnt/d/library_wifi.txt"
[DEBUG][dotdrop.dotdrop.install] installing key:"f_vimrc", src:"vimrc", dst:"~/.vimrc", link:"False"
[DEBUG][dotdrop.installer.install] install /home/roach/dotfiles/dotfiles/vimrc to /home/roach/.vimrc
[DEBUG][dotdrop.installer._handle_file] generate template for /home/roach/dotfiles/dotfiles/vimrc
[DEBUG][dotdrop.utils.run] exec: file -b /home/roach/dotfiles/dotfiles/vimrc
[DEBUG][dotdrop.templategen._handle_file] "/home/roach/dotfiles/dotfiles/vimrc" filetype: UTF-8 Unicode text
[DEBUG][dotdrop.templategen._handle_file] "/home/roach/dotfiles/dotfiles/vimrc" is text: True
```

Now my OS envir is `wsl` + `Ubuntu`.

I'll test it on `Manjaro` later.

**Comment by roachsinai** [comment]
No, there is nothing wrong with install path what I said above. And dotdrop works well on `Manjaro`.

```
➜  share dotdrop install -V
[DEBUG][dotdrop.dotdrop.main] config file: ~/dotfiles/config.yaml
[DEBUG][dotdrop.dotdrop.main] opts: {'backup': True, 'banner': True, 'create': True, 'dotpath': '/home/roach/dotfiles/dotfiles', 'keepdot': False, 'link_by_default': False, 'longkey': False, 'workdir': '~/.config/dotdrop', 'dry': False, 'profile': 'hman', 'safe': True, 'installdiff': True, 'link': False, 'debug': True, 'variables': {}}
     _       _      _
  __| | ___ | |_ __| |_ __ ___  _ __
 / _` |/ _ \| __/ _` | '__/ _ \| '_ |
 \__,_|\___/ \__\__,_|_|  \___/| .__/  v0.21.1
                               |_|

[DEBUG][dotdrop.dotdrop.install] installing key:"f_dircolors", src:"dircolors", dst:"~/.dircolors", link:"False"
[DEBUG][dotdrop.installer.install] install /home/roach/dotfiles/dotfiles/dircolors to /home/roach/.dircolors
[DEBUG][dotdrop.installer._handle_file] generate template for /home/roach/dotfiles/dotfiles/dircolors
[DEBUG][dotdrop.utils.run] exec: file -b /home/roach/dotfiles/dotfiles/dircolors
[DEBUG][dotdrop.templategen._handle_file] "/home/roach/dotfiles/dotfiles/dircolors" filetype: ASCII text
[DEBUG][dotdrop.templategen._handle_file] "/home/roach/dotfiles/dotfiles/dircolors" is text: True
[DEBUG][dotdrop.installer._write] /home/roach/.dircolors is the same
[DEBUG][dotdrop.installer._handle_file] ignoring "/home/roach/.dircolors", same content
[DEBUG][dotdrop.dotdrop.install] installing key:"f_git-diff-wrapper.sh", src:"git-diff-wrapper.sh", dst:"~/.git-diff-wrapper.sh", link:"False"
[DEBUG][dotdrop.installer.install] install /home/roach/dotfiles/dotfiles/git-diff-wrapper.sh to /home/roach/.git-diff-wrapper.sh
[DEBUG][dotdrop.installer._handle_file] generate template for /home/roach/dotfiles/dotfiles/git-diff-wrapper.sh
[DEBUG][dotdrop.utils.run] exec: file -b /home/roach/dotfiles/dotfiles/git-diff-wrapper.sh
[DEBUG][dotdrop.templategen._handle_file] "/home/roach/dotfiles/dotfiles/git-diff-wrapper.sh" filetype: Bourne-Again shell script, ASCII text executable
[DEBUG][dotdrop.templategen._handle_file] "/home/roach/dotfiles/dotfiles/git-diff-wrapper.sh" is text: True
[DEBUG][dotdrop.installer._write] /home/roach/.git-diff-wrapper.sh is the same
[DEBUG][dotdrop.installer._handle_file] ignoring "/home/roach/.git-diff-wrapper.sh", same content
[DEBUG][dotdrop.dotdrop.install] installing key:"f_gitconfig", src:"gitconfig", dst:"~/.gitconfig", link:"False"
[DEBUG][dotdrop.installer.install] install /home/roach/dotfiles/dotfiles/gitconfig to /home/roach/.gitconfig
[DEBUG][dotdrop.installer._handle_file] generate template for /home/roach/dotfiles/dotfiles/gitconfig
[DEBUG][dotdrop.utils.run] exec: file -b /home/roach/dotfiles/dotfiles/gitconfig
[DEBUG][dotdrop.templategen._handle_file] "/home/roach/dotfiles/dotfiles/gitconfig" filetype: UTF-8 Unicode text
[DEBUG][dotdrop.templategen._handle_file] "/home/roach/dotfiles/dotfiles/gitconfig" is text: True
[DEBUG][dotdrop.installer._write] /home/roach/.gitconfig is the same
[DEBUG][dotdrop.installer._handle_file] ignoring "/home/roach/.gitconfig", same content
[DEBUG][dotdrop.dotdrop.install] installing key:"f_library_wifi.txt", src:"mnt/share/library_wifi.txt", dst:"/mnt/share/library_wifi.txt", link:"False"
[DEBUG][dotdrop.installer.install] install /home/roach/dotfiles/dotfiles/mnt/share/library_wifi.txt to /mnt/share/library_wifi.txt
[DEBUG][dotdrop.installer._handle_file] generate template for /home/roach/dotfiles/dotfiles/mnt/share/library_wifi.txt
[DEBUG][dotdrop.utils.run] exec: file -b /home/roach/dotfiles/dotfiles/mnt/share/library_wifi.txt
[DEBUG][dotdrop.templategen._handle_file] "/home/roach/dotfiles/dotfiles/mnt/share/library_wifi.txt" filetype: ASCII text, with CRLF line terminators
[DEBUG][dotdrop.templategen._handle_file] "/home/roach/dotfiles/dotfiles/mnt/share/library_wifi.txt" is text: True
Overwrite "/mnt/share/library_wifi.txt" [y/N] ? y
backup /mnt/share/library_wifi.txt to /mnt/share/library_wifi.txt.dotdropbak
[DEBUG][dotdrop.installer._write] write content to /mnt/share/library_wifi.txt
	-> copied "/home/roach/dotfiles/dotfiles/mnt/share/library_wifi.txt" to "/mnt/share/library_wifi.txt"
[DEBUG][dotdrop.dotdrop.install] installing key:"f_profile", src:"profile", dst:"~/.profile", link:"False"
[DEBUG][dotdrop.installer.install] install /home/roach/dotfiles/dotfiles/profile to /home/roach/.profile
[DEBUG][dotdrop.installer._handle_file] generate template for /home/roach/dotfiles/dotfiles/profile
[DEBUG][dotdrop.utils.run] exec: file -b /home/roach/dotfiles/dotfiles/profile
[DEBUG][dotdrop.templategen._handle_file] "/home/roach/dotfiles/dotfiles/profile" filetype: ASCII text
[DEBUG][dotdrop.templategen._handle_file] "/home/roach/dotfiles/dotfiles/profile" is text: True
[DEBUG][dotdrop.installer._write] /home/roach/.profile is the same
[DEBUG][dotdrop.installer._handle_file] ignoring "/home/roach/.profile", same content
[DEBUG][dotdrop.dotdrop.install] installing key:"f_proxychains.conf", src:"proxychains/proxychains.conf", dst:"~/.proxychains/proxychains.conf", link:"False"
[DEBUG][dotdrop.installer.install] install /home/roach/dotfiles/dotfiles/proxychains/proxychains.conf to /home/roach/.proxychains/proxychains.conf
[DEBUG][dotdrop.installer._handle_file] generate template for /home/roach/dotfiles/dotfiles/proxychains/proxychains.conf
[DEBUG][dotdrop.utils.run] exec: file -b /home/roach/dotfiles/dotfiles/proxychains/proxychains.conf
[DEBUG][dotdrop.templategen._handle_file] "/home/roach/dotfiles/dotfiles/proxychains/proxychains.conf" filetype: ASCII text
[DEBUG][dotdrop.templategen._handle_file] "/home/roach/dotfiles/dotfiles/proxychains/proxychains.conf" is text: True
[DEBUG][dotdrop.installer._write] /home/roach/.proxychains/proxychains.conf is the same
[DEBUG][dotdrop.installer._handle_file] ignoring "/home/roach/.proxychains/proxychains.conf", same content
[DEBUG][dotdrop.dotdrop.install] installing key:"f_vimrc", src:"vimrc", dst:"~/.vimrc", link:"False"
[DEBUG][dotdrop.installer.install] install /home/roach/dotfiles/dotfiles/vimrc to /home/roach/.vimrc
[DEBUG][dotdrop.installer._handle_file] generate template for /home/roach/dotfiles/dotfiles/vimrc
[DEBUG][dotdrop.utils.run] exec: file -b /home/roach/dotfiles/dotfiles/vimrc
[DEBUG][dotdrop.templategen._handle_file] "/home/roach/dotfiles/dotfiles/vimrc" filetype: UTF-8 Unicode text
[DEBUG][dotdrop.templategen._handle_file] "/home/roach/dotfiles/dotfiles/vimrc" is text: True
[DEBUG][dotdrop.installer._write] /home/roach/.vimrc is the same
[DEBUG][dotdrop.installer._handle_file] ignoring "/home/roach/.vimrc", same content
[DEBUG][dotdrop.dotdrop.install] installing key:"f_zshrc", src:"zshrc", dst:"~/.zshrc", link:"False"
[DEBUG][dotdrop.installer.install] install /home/roach/dotfiles/dotfiles/zshrc to /home/roach/.zshrc
[DEBUG][dotdrop.installer._handle_file] generate template for /home/roach/dotfiles/dotfiles/zshrc
[DEBUG][dotdrop.utils.run] exec: file -b /home/roach/dotfiles/dotfiles/zshrc
[DEBUG][dotdrop.templategen._handle_file] "/home/roach/dotfiles/dotfiles/zshrc" filetype: UTF-8 Unicode text
[DEBUG][dotdrop.templategen._handle_file] "/home/roach/dotfiles/dotfiles/zshrc" is text: True
Overwrite "/home/roach/.zshrc" [y/N] ? n
[WARN] ignoring "/home/roach/.zshrc", already present 
[DEBUG][dotdrop.installer._handle_file] ignoring "/home/roach/.zshrc", same content

1 dotfile(s) installed.
```

So, the error on wsl is just because dotfile is not copied to the `dotpath`.

By the way wsl ubuntu python versiom is 3.6, and Manjaro is 3.7.

**Comment by deadc0de6** [comment]
Ok, thanks for the info. Python 3.6 vs 3.7 shouldn't make a difference. Can you try on WSL to remove `library_wifi.txt` and re-import it with `-V` to see what is being done?

First make a backup of the file (`cp /home/roach/dotfiles/dotfiles/mnt/share/library_wifi.txt /tmp/library_wifi.txt.bak`, remove it from the dotpath (`rm /home/roach/dotfiles/dotfiles/mnt/share/library_wifi.txt`) and then remove it from the config file (from the `dotfiles` entry and the `profile` entry).

Then try to re-import it with the debug logs on WSL:
```bash
dotdrop import library_wifi.txt -V
```

Hopefully this will gives us more info on why it is not copied on WSL.

**Comment by roachsinai** [comment]
Hi, @deadc0de6 the First step cannot success, cause after I import `library_wifi.txt`, `library_wifi.txt` actually not copy to `dotpath`.

```
➜  d dotdrop import library_wifi.txt -V
[DEBUG][dotdrop.dotdrop.main] config file: ~/dotfiles/config.yaml
[DEBUG][dotdrop.dotdrop.main] opts: {'backup': True, 'banner': True, 'create': True, 'dotpath': '/home/roach/dotfiles/dotfiles', 'keepdot': False, 'link_by_default': False, 'longkey': False, 'workdir': '~/.config/dotdrop', 'dry': False, 'profile': 'hwin', 'safe': True, 'installdiff': True, 'link': False, 'debug': True, 'variables': {}}
     _       _      _
  __| | ___ | |_ __| |_ __ ___  _ __
 / _` |/ _ \| __/ _` | '__/ _ \| '_ |
 \__,_|\___/ \__\__,_|_|  \___/| .__/  v0.21.1
                               |_|

[DEBUG][dotdrop.utils.run] exec: mkdir -p /home/roach/dotfiles/dotfiles/mnt/d
[DEBUG][dotdrop.utils.run] exec: cp -R -L /mnt/d/library_wifi.txt /home/roach/dotfiles/dotfiles/mnt/d/library_wifi.txt
        -> "library_wifi.txt" imported

1 file(s) imported.
➜  d
```

And the patition which keep `library_wifi.txt` mounted at `/mnt/share` on Manjaro, mounted at `/mnt/d` on wsl.

```
➜  dotfiles git:(master) ✗ tree
.
├── dircolors
├── git-diff-wrapper.sh
├── gitconfig
├── mnt
│   └── d
├── profile
├── proxychains
│   └── proxychains.conf
├── vimrc
└── zshrc

3 directories, 7 files
➜  dotfiles git:(master) ✗ cd mnt/d
➜  d git:(master) ✗ la
total 0
➜  d git:(master) ✗ pwd
/home/roach/dotfiles/dotfiles/mnt/d
➜  d git:(master) ✗
```

**Comment by deadc0de6** [comment]
hm interesting, I will add some checks to print an error when a command fails (for example for `cp` or `ln`). By chown/chmod the file, are you able to import and install it then ?

**Comment by roachsinai** [comment]
Yep,

```
➜  d dpim library_wifi.txt
     _       _      _
  __| | ___ | |_ __| |_ __ ___  _ __
 / _` |/ _ \| __/ _` | '__/ _ \| '_ |
 \__,_|\___/ \__\__,_|_|  \___/| .__/  v0.21.1
                               |_|

        -> "library_wifi.txt" imported

1 file(s) imported.
➜  d z dot dot
➜  dotfiles git:(master) ✗ tree
.
├── dircolors
├── git-diff-wrapper.sh
├── gitconfig
├── mnt
│   └── d
│       └── library_wifi.txt
├── profile
├── proxychains
│   └── proxychains.conf
├── vimrc
└── zshrc

3 directories, 8 files
```

The file mode are normal on Manjaro. Don't know why. though WSL is moving on.

**Comment by deadc0de6** [comment]
I just released a new version on pypi.
It should now outputs an error when it is unable to import a dotfile:
```
[ERR] "cp -R -L /mnt/a /home/user/dotfiles/dotfiles/mnt/a" returned non zero (1): cp: cannot open '/mnt/a' for reading: Permission denied 
[ERR] importing "/mnt/a" failed!
```

**Comment by roachsinai** [comment]
Yes, it is.

**Comment by deadc0de6** [comment]
awesome :+1:
