### ISSUE TITLE
Install on Termux fails

### ISSUE THREAD

**Issue by ReekyMarko** [deadc0de6/dotdrop#78]
Trying to `dotdrop install` on [Termux](https://termux.com/) results in the following error:

```
$ ./dotdrop.sh --version
0.24.1
$ ./dotdrop.sh install
     _       _      _
  __| | ___ | |_ __| |_ __ ___  _ __
 / _` |/ _ \| __/ _` | '__/ _ \| '_ |
 \__,_|\___/ \__\__,_|_|  \___/| .__/  v0.24.1
                               |_|

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data/data/com.termux/files/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/data/com.termux/files/home/Git/dotfiles/dotdrop/dotdrop/dotdrop.py", line 509, in <module>
    if main():
  File "/data/data/com.termux/files/home/Git/dotfiles/dotdrop/dotdrop/dotdrop.py", line 466, in main
    keys=args['<key>'])
  File "/data/data/com.termux/files/home/Git/dotfiles/dotdrop/dotdrop/dotdrop.py", line 120, in cmd_install
    noempty=dotfile.noempty)
  File "/data/data/com.termux/files/home/Git/dotfiles/dotdrop/dotdrop/installer.py", line 56, in install
    noempty=noempty)
  File "/data/data/com.termux/files/home/Git/dotfiles/dotdrop/dotdrop/installer.py", line 162, in _handle_dir
    actions=actions, noempty=noempty)
  File "/data/data/com.termux/files/home/Git/dotfiles/dotdrop/dotdrop/installer.py", line 124, in _handle_file
    content = templater.generate(src)
  File "/data/data/com.termux/files/home/Git/dotfiles/dotdrop/dotdrop/templategen.py", line 54, in generate
    return self._handle_file(src)
  File "/data/data/com.termux/files/home/Git/dotfiles/dotdrop/dotdrop/templategen.py", line 69, in _handle_file
    raw=False, debug=self.debug)
  File "/data/data/com.termux/files/home/Git/dotfiles/dotdrop/dotdrop/utils.py", line 27, in run
    stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "/data/data/com.termux/files/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/data/data/com.termux/files/usr/lib/python3.7/subprocess.py", line 1520, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'file': 'file'
```

Any idea what could cause this?

**Comment by duckunix** [comment]
Your install is missing the 'file' command.  Simply run **pkg install file**, then rerun the dotdrop command.

**Comment by deadc0de6** [comment]
@duckunix is right, dotdrop uses the unix tool `file` to identify the filetype when generating templates. I have added the few dependencies on this wiki page: <https://github.com/deadc0de6/dotdrop/wiki/dependencies>

**Comment by ReekyMarko** [comment]
Thanks a bunch! Works perfectly
